### ISSUE TITLE
Add dependency on dialog

### ISSUE THREAD

**Issue by Vanuan** [MrMEEE/ironhide#10]
Without dialog package it doesn't work.

**Comment by MrMEEE** [comment]
Doesn't dialog or zenity get installed by default on Ubuntu???

It works by default on Kubuntu with kdialog..

**Comment by Web-E** [comment]
I am having some error message saying that dialog is obsolete, install cdialog and alias it like that

**Comment by Vanuan** [comment]
For me it wasn't installed. I had to do apt-get install dialog.

Even if it was installed by default, it could be removed by user. User doesn't have to know all dependencies of all packages.

**Comment by MrMEEE** [comment]
Will add dialog as dependency,,,
