### ISSUE TITLE
Dell N5110

### ISSUE THREAD

**Issue by MrMEEE** [MrMEEE/ironhide#104]
My name is Ben Adler and I need help! I'm running a Dell N5110 Intel i5 with Ubuntu 11.04. I have an Intel default graphics card and a discrete NVIDIA although I don't know the model. I tried to use bumblebee a while ago and it told me that there was no module found to enable/disable it and it wouldn't work...with Ironhide it tells me that it could not find the BusID and that I need to manually configure it in my xorg.conf.nvidia file. I understand where this file is and how to edit it, but do not know exactly what I'm supposed to do. Can you help me with that? Also, I do not currently have the NVIDIA driver installed because when I install it, it creates and configures a new xorg.conf file in my /etc/X11 directory, causing my computer to reboot to a blank screen.

**Comment by MrMEEE** [comment]
Here is the output of when I installed Ironhide:

ben@ben-Inspiron-N5110:~$ sudo apt-get install ironhide
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following extra packages will be installed:
  acpi-call-dkms curl easybashgui virtualgl
The following NEW packages will be installed:
  acpi-call-dkms curl easybashgui ironhide virtualgl
0 upgraded, 5 newly installed, 0 to remove and 4 not upgraded.
Need to get 1,858 kB of archives.
After this operation, 6,058 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://ppa.launchpad.net/mj-casalogic/ironhide/ubuntu/ natty/main acpi-call-dkms all 240611-1~nattyubuntu1 [6,080 B]
Get:2 http://us.archive.ubuntu.com/ubuntu/ natty-updates/main curl amd64 7.21.3-1ubuntu1.3 [181 kB]
Get:3 http://ppa.launchpad.net/mj-casalogic/ironhide/ubuntu/ natty/main easybashgui amd64 1.3.1-1~nattyubuntu4 [36.0 kB]
Get:4 http://ppa.launchpad.net/mj-casalogic/ironhide/ubuntu/ natty/main virtualgl amd64 2.2.91-1~nattyubuntu2 [1,570 kB]
Get:5 http://ppa.launchpad.net/mj-casalogic/ironhide/ubuntu/ natty/main ironhide amd64 1.0-1~nattyubuntu37 [65.3 kB]
Fetched 1,858 kB in 2s (867 kB/s) 
Selecting previously deselected package acpi-call-dkms.
(Reading database ... 297826 files and directories currently installed.)
Unpacking acpi-call-dkms (from .../acpi-call-dkms_240611-1~nattyubuntu1_all.deb) ...
Selecting previously deselected package curl.
Unpacking curl (from .../curl_7.21.3-1ubuntu1.3_amd64.deb) ...
Selecting previously deselected package easybashgui.
Unpacking easybashgui (from .../easybashgui_1.3.1-1~nattyubuntu4_amd64.deb) ...
Selecting previously deselected package virtualgl.
Unpacking virtualgl (from .../virtualgl_2.2.91-1~nattyubuntu2_amd64.deb) ...
Selecting previously deselected package ironhide.
Unpacking ironhide (from .../ironhide_1.0-1~nattyubuntu37_amd64.deb) ...
Processing triggers for man-db ...
Processing triggers for ureadahead ...
ureadahead will be reprofiled on next reboot
Setting up acpi-call-dkms (240611-1~nattyubuntu1) ...

Creating symlink /var/lib/dkms/acpi-call/240611/source ->
                 /usr/src/acpi-call-240611

DKMS: add Completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area....
make KERNELRELEASE=2.6.38-11-server IGNORE_CC_MISMATCH=1 KDIR=/lib/modules/2.6.38-11-server/build PWD=/var/lib/dkms/acpi-call/240611/build....
cleaning build area....

DKMS: build Completed.

acpi_call.ko:
Running module version sanity check.
- Original module
  - No original module exists within this kernel
- Installation
  - Installing to /lib/modules/2.6.38-11-server/updates/dkms/

depmod....

DKMS: install Completed.
Setting up curl (7.21.3-1ubuntu1.3) ...
Setting up easybashgui (1.3.1-1~nattyubuntu4) ...
Setting up virtualgl (2.2.91-1~nattyubuntu2) ...
Setting up ironhide (1.0-1~nattyubuntu37) ...
Installing new version of config file /etc/bash_completion.d/optirun ...
1
AUTO

And this is my lspci output:

ben@ben-Inspiron-N5110:~$ lspci
00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09)
00:16.0 Communication controller: Intel Corporation 6 Series Chipset Family MEI Controller #1 (rev 04)
00:1a.0 USB Controller: Intel Corporation 6 Series Chipset Family USB Enhanced Host Controller #2 (rev 05)
00:1b.0 Audio device: Intel Corporation 6 Series Chipset Family High Definition Audio Controller (rev 05)
00:1c.0 PCI bridge: Intel Corporation 6 Series Chipset Family PCI Express Root Port 1 (rev b5)
00:1c.1 PCI bridge: Intel Corporation 6 Series Chipset Family PCI Express Root Port 2 (rev b5)
00:1c.3 PCI bridge: Intel Corporation 6 Series Chipset Family PCI Express Root Port 4 (rev b5)
00:1c.4 PCI bridge: Intel Corporation 6 Series Chipset Family PCI Express Root Port 5 (rev b5)
00:1c.7 PCI bridge: Intel Corporation 6 Series Chipset Family PCI Express Root Port 8 (rev b5)
00:1d.0 USB Controller: Intel Corporation 6 Series Chipset Family USB Enhanced Host Controller #1 (rev 05)
00:1f.0 ISA bridge: Intel Corporation HM67 Express Chipset Family LPC Controller (rev 05)
00:1f.2 SATA controller: Intel Corporation 6 Series Chipset Family 6 port SATA AHCI Controller (rev 05)
00:1f.3 SMBus: Intel Corporation 6 Series Chipset Family SMBus Controller (rev 05)
05:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8101E/RTL8102E PCI Express Fast Ethernet controller (rev 05)
09:00.0 Network controller: Intel Corporation Centrino Wireless-N 1030 (rev 34)
0b:00.0 USB Controller: NEC Corporation uPD720200 USB 3.0 Host Controller (rev 04)

**Comment by MrMEEE** [comment]
It seems like your nVidia card is disabled.. could you please check your BIOS for any Optimus/nVidia settings??

**Comment by benjaminalgreen** [comment]
I checked my BIOS for OPtimux/nVidia settings and found none. 

I can post the output if you would like.

**Comment by benjaminalgreen** [comment]
So how do I enable the NVIDIA graphics card if it is currently disabled? I can't access it through ironhide...

**Comment by benjaminalgreen** [comment]
Is it possible to get a bump on this? Perhaps reinstalling ubuntu as 32bit? Would that help?

**Comment by benjaminalgreen** [comment]
Apparently Dell was dumb about it and forgot to include the NVIDIA graphics card in my order. I'm getting a replacement please close the topic.
