### ISSUE TITLE
Fresh install issues 1215n

### ISSUE THREAD

**Issue by Benchamoneh** [MrMEEE/ironhide#11]
Ok I've just installed ironhide on a fresh 11.04 install and I have a few issues. After configuring my laptop (using the script by Nicolas Joyard) I could optirun glxgears and would be getting about 60fps, however running glxgears without optirun returned: "Error: couldn't get an RGB, Double-bufferred visual". Now that I've unplugged my laptop from the mains I get this error no matter if I use optirun or not. Additionally ironhide-enablecard and ironhide-disablecard appear to do nothing (whether run as root or not discharge rate does not change). Any ideas or logs I can submit?

P.S. I was having issues with the configuration script bringing up gears but this was solved by installing mesa-utils, perhaps a check for this needs to be added in future?

**Comment by MrMEEE** [comment]
If you haven't:

Please try to:

rm /usr/local/bin/ironhide*

reboot

then rerun installation...

and see if problem persists...

In regards to the mesa-utils, the check was already there, just wasn't working.. it should be fixed in latest release...

**Comment by Benchamoneh** [comment]
That solved the double-buffered visual error but ironhide doesn't seem to be using the nvidia card. I'm getting 60fps on glxgears with or without optirun. I remember using the old bumblebee configuration that I'd get about 60fps on the intel card and ~280fps with the nv chip

**Comment by MrMEEE** [comment]
ok...

could you please run the ironhide-bugreport utility??

**Comment by forall** [comment]
Hello
I installed a bumblebee script and I runing glxgears and I have average 56 fps without optirun, after using optirun I get average results 270 fps, nvidia working?
Someone testing mplayer with hd movies and optirun?

**Comment by MrMEEE** [comment]
@forall: I sound like it's working..

vdpau, which mplayer use for acceleration, doesn't work with ironhide/bumblebee...

**Comment by MrMEEE** [comment]
@Benchamoneh: 

Could you try to use the ironhide-settings utility to change the image transport to jpeg, and see if you get better fps there???

**Comment by LorenzoBettini** [comment]
I tried to reinstall ironhide as suggested in this issue, but when running ironhide-configuration I still get

Error: couldn't get an RGB, Double-buffered visual
Another ironhide powered application is running, keeping ironhide alive.
