### ISSUE TITLE
problems after last update

### ISSUE THREAD

**Issue by pawel1611** [MrMEEE/ironhide#12]
11.04 64bit

pawel@pawel-U31Jg:~$ sudo ironhide-configuration [sudo] password for pawel: 
grep: /etc/X11/xorg.conf.nvidia: No such file or directory
grep: /etc/X11/xorg.conf.nvidia: No such file or directory
grep: /etc/X11/xorg.conf.nvidia: No such file or directory
0
MANUAL
_PS0 Disabling nVidia Card Succeded.
- Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
- Stopping Ironhide X server ironhide                                   [fail] 
- Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
- Stopping Ironhide X server ironhide                                   [fail] 
  System start/stop links for /etc/init.d/ironhide already exist.
  Adding user pawel to group ironhide

pawel@pawel-U31Jg:~$ sudo optirun64 chrome
grep: /etc/X11/xorg.conf.nvidia: No such file or directory
- Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia Card Succeded.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
  ironhide could not be started - optirun cannot be executed.

pawel@pawel-U31Jg:~$ cat /var/log/Xorg.8.log
[   261.780] 
X.Org X Server 1.10.3.902 (1.10.4 RC 2)
Release Date: 2011-08-12
[   261.781] X Protocol Version 11, Revision 0
[   261.781] Build Operating System: Linux 2.6.24-29-xen x86_64 Ubuntu
[   261.781] Current Operating System: Linux pawel-U31Jg 2.6.38-11-generic #48-Ubuntu SMP Fri Jul 29 19:02:55 UTC 2011 x86_64
[   261.781] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.38-11-generic root=UUID=6af922ba-d438-4273-ac1d-f1c23d7aa7a7 ro quiet splash vt.handoff=7
[   261.781] Build Date: 15 August 2011  03:52:57PM
[   261.781] xorg-server 2:1.10.3.902+git20110815+server-1.10-branch.4597f201-0ubuntu0sarvatt~natty (For technical support please see http://www.ubuntu.com/support) 
[   261.781] Current version of pixman: 0.21.8
[   261.781]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[   261.781] Markers: (--) probed, (*_) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   261.781](==) Log file: "/var/log/Xorg.8.log", Time: Thu Aug 25 23:03:58 2011
[   261.781](EE) Unable to locate/open config file: "/etc/X11/xorg.conf.nvidia"
[   261.781](==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   261.781](==) No Layout section.  Using the first Screen section.
[   261.781](==) No screen section available. Using defaults.
[   261.781](**) |-->Screen "Default Screen Section" (0)
[   261.781](**) |   |-->Monitor "<default monitor>"
[   261.782](==) No monitor specified for screen "Default Screen Section".
    Using a default monitor configuration.
[   261.782](==) Automatically adding devices
[   261.782](==) Automatically enabling devices
[   261.782](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   261.782]    Entry deleted from font path.
[   261.782](WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   261.782]    Entry deleted from font path.
[   261.782](WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   261.782]    Entry deleted from font path.
[   261.782](WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   261.782]    Entry deleted from font path.
[   261.782](WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   261.782]    Entry deleted from font path.
[   261.782](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/Type1,
    /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,
    built-ins
[   261.782](++) ModulePath set to "/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules"
[   261.782](II) The server relies on udev to provide the list of input devices.
    If no devices become available, reconfigure udev or disable AutoAddDevices.
[   261.782](II) Loader magic: 0x7e3860
[   261.782](II) Module ABI versions:
[   261.782]    X.Org ANSI C Emulation: 0.4
[   261.782]    X.Org Video Driver: 10.0
[   261.782]    X.Org XInput driver : 12.3
[   261.782]    X.Org Server Extension : 5.0
[   261.783](--) PCI:_(0:0:2:0) 8086:0046:1043:1552 rev 24, Mem @ 0xd3400000/4194304, 0xb0000000/268435456, I/O @ 0x0000e080/8
[   261.783](--) PCI: (0:1:0:0) 10de:0dee:1043:1552 rev 161, Mem @ 0xd2000000/16777216, 0xc0000000/268435456, 0xd0000000/33554432, I/O @ 0x0000d000/128, BIOS @ 0x????????/524288
[   261.784](II) Open ACPI successful (/var/run/acpid.socket)
[   261.784](II) LoadModule: "extmod"
[   261.784](II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[   261.784](II) Module extmod: vendor="X.Org Foundation"
[   261.784]    compiled for 1.10.3.902, module version = 1.0.0
[   261.784]    Module class: X.Org Server Extension
[   261.784]    ABI class: X.Org Server Extension, version 5.0
[   261.784](II) Loading extension MIT-SCREEN-SAVER
[   261.784](II) Loading extension XFree86-VidModeExtension
[   261.784](II) Loading extension XFree86-DGA
[   261.784](II) Loading extension DPMS
[   261.784](II) Loading extension XVideo
[   261.784](II) Loading extension XVideo-MotionCompensation
[   261.784](II) Loading extension X-Resource
[   261.784](II) LoadModule: "dbe"
[   261.785](II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[   261.785](II) Module dbe: vendor="X.Org Foundation"
[   261.785]    compiled for 1.10.3.902, module version = 1.0.0
[   261.785]    Module class: X.Org Server Extension
[   261.785]    ABI class: X.Org Server Extension, version 5.0
[   261.785](II) Loading extension DOUBLE-BUFFER
[   261.785](II) LoadModule: "glx"
[   261.785](II) Loading /usr/lib/nvidia-current/xorg/libglx.so
[   261.800](II) Module glx: vendor="NVIDIA Corporation"
[   261.800]    compiled for 4.0.2, module version = 1.0.0
[   261.800]    Module class: X.Org Server Extension
[   261.800](II) NVIDIA GLX Module  285.03  Mon Aug 15 02:52:52 PDT 2011
[   261.800](II) Loading extension GLX
[   261.800](II) LoadModule: "record"
[   261.800](II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[   261.800](II) Module record: vendor="X.Org Foundation"
[   261.800]    compiled for 1.10.3.902, module version = 1.13.0
[   261.800]    Module class: X.Org Server Extension
[   261.800]    ABI class: X.Org Server Extension, version 5.0
[   261.800](II) Loading extension RECORD
[   261.800](II) LoadModule: "dri"
[   261.800](II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[   261.800](II) Module dri: vendor="X.Org Foundation"
[   261.800]    compiled for 1.10.3.902, module version = 1.0.0
[   261.800]    ABI class: X.Org Server Extension, version 5.0
[   261.800](II) Loading extension XFree86-DRI
[   261.800](II) LoadModule: "dri2"
[   261.801](II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[   261.801](II) Module dri2: vendor="X.Org Foundation"
[   261.801]    compiled for 1.10.3.902, module version = 1.2.0
[   261.801]    ABI class: X.Org Server Extension, version 5.0
[   261.801](II) Loading extension DRI2
[   261.801](==) Matched intel as autoconfigured driver 0
[   261.801](==) Matched vesa as autoconfigured driver 1
[   261.801](==) Matched fbdev as autoconfigured driver 2
[   261.801](==) Assigned the driver to the xf86ConfigLayout
[   261.801](II) LoadModule: "intel"
[   261.801](II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[   261.801](II) Module intel: vendor="X.Org Foundation"
[   261.801]    compiled for 1.10.3.902, module version = 2.16.0
[   261.801]    Module class: X.Org Video Driver
[   261.801]    ABI class: X.Org Video Driver, version 10.0
[   261.801](II) LoadModule: "vesa"
[   261.801](II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[   261.801](II) Module vesa: vendor="X.Org Foundation"
[   261.801]    compiled for 1.10.1, module version = 2.3.0
[   261.801]    Module class: X.Org Video Driver
[   261.801]    ABI class: X.Org Video Driver, version 10.0
[   261.801](II) LoadModule: "fbdev"
[   261.801](II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[   261.801](II) Module fbdev: vendor="X.Org Foundation"
[   261.801]    compiled for 1.10.1, module version = 0.4.2
[   261.802]    Module class: X.Org Video Driver
[   261.802]    ABI class: X.Org Video Driver, version 10.0
[   261.802](II) intel: Driver for Intel Integrated Graphics Chipsets: i810,
    i810-dc100, i810e, i815, i830M, 845G, 854, 852GM/855GM, 865G, 915G,
    E7221 (i915), 915GM, 945G, 945GM, 945GME, Pineview GM, Pineview G,
    965G, G35, 965Q, 946GZ, 965GM, 965GME/GLE, G33, Q35, Q33, GM45,
    4 Series, G45/G43, Q45/Q43, G41, B43, B43, Clarkdale, Arrandale,
    Sandybridge Desktop (GT1), Sandybridge Desktop (GT2),
    Sandybridge Desktop (GT2+), Sandybridge Mobile (GT1),
    Sandybridge Mobile (GT2), Sandybridge Mobile (GT2+),
    Sandybridge Server, Ivybridge Mobile (GT1), Ivybridge Mobile (GT2),
    Ivybridge Desktop (GT1), Ivybridge Desktop (GT2), Ivybridge Server
[   261.802](II) VESA: driver for VESA chipsets: vesa
[   261.802](II) FBDEV: driver for framebuffer: fbdev
[   261.802](--) using VT number 7

[   261.802](WW) xf86OpenConsole: setpgid failed: Operation not permitted
[   261.804](II) Loading /usr/lib/xorg/modules/drivers/intel_drv.so
[   261.804](WW) Falling back to old probe method for vesa
[   261.804](WW) Falling back to old probe method for fbdev
[   261.804](II) Loading sub module "fbdevhw"
[   261.804](II) LoadModule: "fbdevhw"
[   261.804](II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[   261.804](II) Module fbdevhw: vendor="X.Org Foundation"
[   261.804]    compiled for 1.10.3.902, module version = 0.0.2
[   261.804]    ABI class: X.Org Video Driver, version 10.0
[   261.804] drmOpenDevice: node name is /dev/dri/card0
[   261.804] drmOpenDevice: open result is 9, (OK)
[   261.804] drmOpenByBusid: Searching for BusID pci:0000:00:02.0
[   261.804] drmOpenDevice: node name is /dev/dri/card0
[   261.804] drmOpenDevice: open result is 9, (OK)
[   261.805] drmOpenByBusid: drmOpenMinor returns 9
[   261.805] drmOpenByBusid: Interface 1.4 failed, trying 1.1
[   261.805] drmOpenByBusid: drmGetBusid reports pci:0000:00:02.0
[   261.805](EE) intel(0): [drm] failed to set drm interface version.
[   261.805](EE) intel(0): Failed to become DRM master.
[   261.805](II) intel(0): Creating default Display subsection in Screen section
    "Default Screen Section" for depth/fbbpp 24/32
[   261.805](==) intel(0): Depth 24, (--) framebuffer bpp 32
[   261.805](==) intel(0): RGB weight 888
[   261.805](==) intel(0): Default visual is TrueColor
[   261.805](II) intel(0): Integrated Graphics Chipset: Intel(R) Arrandale
[   261.805](--) intel(0): Chipset: "Arrandale"
[   261.805](**) intel(0): Relaxed fencing disabled
[   261.805](**) intel(0): Wait on SwapBuffers? enabled
[   261.805](**) intel(0): Triple buffering? enabled
[   261.805](**) intel(0): Framebuffer tiled
[   261.805](**) intel(0): Pixmaps tiled
[   261.805](**) intel(0): 3D buffers tiled
[   261.805](**) intel(0): SwapBuffers wait enabled
[   261.805](==) intel(0): video overlay key set to 0x101fe
[   261.805](EE) intel(0): failed to get resources: Bad file descriptor
[   261.805](II) UnloadModule: "intel"
[   261.805](II) Unloading intel
[   261.805](EE) Screen(s) found, but none have a usable configuration.
[   261.805] 
Fatal server error:
[   261.805] no screens found
[   261.805] 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[   261.805] Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[   261.805] 
[   261.805]  ddxSigGiveUp: Closing log

**Comment by MrMEEE** [comment]
Please try to:

apt-get remove ironhide
apt-get install ironhide

don't know how you got /etc/X11/xorg.conf.nvidia deleted???

**Comment by pawel1611** [comment]
I tried to "reinstall" ironhide few times and every time is the same issue. I had also "reinstalled" nvidia-current (I use X-org edgers repository) and even disable/enable proprietary drivers in additional drivers. Still the same problem.

I think that /etc/X11/xorg.conf.nvidia was deleted during reinstall of ironhide or nvidia-current. Do you have any idea how to restore it?

**Comment by MrMEEE** [comment]
the file is in the ironhide package...

try to do a:

apt-get purge ironhide
apt-get install ironhide

**Comment by pawel1611** [comment]
your solution (the easiest solution) worked for me
sorry for wasting your time :)

but its still interesting why update destroyed my ironhide :(
