### ISSUE TITLE
Instalation Problems

### ISSUE THREAD

**Issue by webbsimax** [MrMEEE/ironhide#13]
Hi,

Trying to install Ironhide (had bumble bee working previously, now uninstalled) . I get the following:
"
adam@delta:~$ sudo ironhide-configuration 
1
AUTO
Error: acpi_call module not loaded
- Starting Ironhide X server ironhide  
  Ironhide hasn't been configured for power management, please run ironhide-configuration.
  ... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current  
- The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
- Stopping Ironhide X server ironhide                                   [fail] 
  Error: acpi_call module not loaded
- Starting Ironhide X server ironhide  
  Error: acpi_call module not loaded
  ... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current  
- The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
- Stopping Ironhide X server ironhide                                   [fail] 
  System start/stop links for /etc/init.d/ironhide already exist.
  Adding user adam to group ironhide
  "

When I try
:~$ sudo modprobe nvidia-current 
I dont get any output. 

I have the latest nVidia drivers from the repository, and a GEFORCE GT 550M graphics card. 

Any suggestions?

Cheers

Adam

**Comment by Web-E** [comment]
Remove ironhide , nvidia drivers, acpi call.
Reboot.
Install all except ironhide ,
```sudo apt-get install nvidia-current nvidia-settings acpi-call-dkms

``````
Reboot
Install IronHide

```sudo apt-get install ronhide ```

Then open ```/etc/X11/xorg.conf.nvidia``` and change:
 ```Option ConnectedMonitor CRT-0``` to ```Option ConnectedMonitor DFP-0``` . After that, try to configure.
``````

**Comment by MrMEEE** [comment]
please run the ironhide-bugreport utility..

**Comment by webbsimax** [comment]
Done the above, and submitted bug report. I now get 

> > sudo ironhide-configuration 
> > 1
> > AUTO
> > - Starting Ironhide X server ironhide  
> >   Ironhide hasn't been configured for power management, please run ironhide-configuration.
> >   ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
> > - Stopping Ironhide X server ironhide                                   [fail] 
> >   Error: could not unload nvidia module, leaving card turned on
> > - Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia Card Succeded.
> >   ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                      [fail] 
> > - Stopping Ironhide X server ironhide                                   [fail] 
> >   System start/stop links for /etc/init.d/ironhide already exist.

I can attach the Xorg log file, is there a nice way to attach without pasting the whole file in to here?

**Comment by MrMEEE** [comment]
Try using the ironhide-settings utility to change the connectedmonitor to DFP-0

**Comment by MrMEEE** [comment]
The log was submitted in the bugreport

**Comment by MrMEEE** [comment]
Please reopen if problem persists...

**Comment by alm6iri** [comment]
Please Support BackTrack 5 > Ubuntu 10.04
I Hav BackTrack 5r3 KDE But I can't Install The Bumblebee
Is there a solution ?

**Comment by MrMEEE** [comment]
Hi.. 

Ironhide is outdated... 

Look at "http://bumblebee-project.org/" instead... 

Best of luck.. 

----- Original meddelelse -----

Fra: "alm6iri" notifications@github.com 
Til: "MrMEEE/ironhide" ironhide@noreply.github.com 
Sendt: onsdag, 31. juli 2013 22:29:40 
Emne: Re: [ironhide] Instalation Problems (#13) 

Please Support BackTrack 5 > Ubuntu 10.04 
I Hav BackTrack 5r3 KDE But I can't Install The Bumblebee 
Is there a solution ?
