### ISSUE TITLE
Uninstall of Ironhide does not remove downloads

### ISSUE THREAD

**Issue by LeeNX** [MrMEEE/ironhide#131]
Having problems with getting IronHide to work again on my Asus N61J, with Ubuntu 11.10, I see the error -
var/lib/dpkg/info/ironhide.postrm: 42: [[: not found

I believe this error stops the downloads from been deleted.

root@LeeT-U64D-NB:~# apt-get remove ironhide
Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages will be REMOVED:
  ironhide ironhide-ui
0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
After this operation, 2,200 kB disk space will be freed.
Do you want to continue [Y/n]? y
(Reading database ... 299516 files and directories currently installed.)
Removing ironhide-ui ...
Removing ironhide ...
GFX._ON Enabling nVidia Card Succeded.
/var/lib/dpkg/info/ironhide.postrm: 42: [[: not found
Processing triggers for desktop-file-utils ...
Processing triggers for gnome-menus ...
Processing triggers for bamfdaemon ...
Rebuilding /usr/share/applications/bamf.index...
Processing triggers for ureadahead ...
root@LeeT-U64D-NB:~#

**Comment by MrMEEE** [comment]
This should be fixed in version ubuntu39, which is building right now.. please reopen if problem persists..
