### ISSUE TITLE
Configuration problem on Ubuntu 11.10

### ISSUE THREAD

**Issue by adilek** [MrMEEE/ironhide#134]
I have a problem when configuring ironhide. 
It says
The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log

It worked me on Ubuntu 11.04 with bumblebee. After upgrading to 11.10 it doesn't works. I deleted bumblebee and installed the ironhide. No effect :(

**Comment by MrMEEE** [comment]
Have you tried with the 280.13 nvidia driver???

**Comment by adilek** [comment]
After configuration it gives me an error on configuration tool. 
Power configuration tests failed.

I'll try 280.13 now.

**Comment by adilek** [comment]
Same problem with additions: 
adil@adil-U43Jc:~$ optirun glxinfo 
- Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia card succeeded.
  FATAL: Module nvidia_current not found.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
  ironhide could not be started - optirun cannot be executed.

**Comment by adilek** [comment]
Reinstalled nvidia 280.13 drivers and ironhide. Works fine. 
Thanks for excellent driver.
