### ISSUE TITLE
Ironhide not working after last update(10/2010)

### ISSUE THREAD

**Issue by NaKroTeK** [MrMEEE/ironhide#137]
Since i try to update ironhide, it's stuck with the nvidia libs
and impossible to make any move !

Reinstall don't change anythings !!!

what should i do ?

Asus U35J ubuntu 11.04

**Comment by MrMEEE** [comment]
have you tried rerunning the ironhide-configuration??

could you please run ironhide-bugreport

**Comment by NaKroTeK** [comment]
I tried before, and it could not detect the graphic card.
then i launched a bugreprot and don't see what was going on !!

I could not run ironhide anymore since i removed it : 

Certains paquets ne peuvent être installés. Ceci peut signifier
que vous avez demandé l'impossible, ou bien, si vous utilisez
la distribution unstable, que certains paquets n'ont pas encore
été créés ou ne sont pas sortis d'Incoming.
L'information suivante devrait vous aider à résoudre la situation : 

Les paquets suivants contiennent des dépendances non satisfaites :
 ironhide : Dépend: nvidia-current mais ne sera pas installé
E: Paquets défectueux

**Comment by NaKroTeK** [comment]
in english maybe? :
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ironhide : Depends: nvidia-current but it is not going to be installed
E: Broken packages

**Comment by NaKroTeK** [comment]
So the fix was to reinstall with xorg-edgers ppa enable
then running the configuration tool....

Question : grep rate /proc/acpi/battery/BAT0/state
i got nothing with this is it normal ?
