### ISSUE TITLE
/etc/defaults/ironhide shouldn't clobber settings

### ISSUE THREAD

**Issue by benjaminjkraft** [MrMEEE/ironhide#14]
Right now, the settings in /etc/defaults/ironhide can't be changed on a per-use basis.  It would be nice if it did not set environment variables that were already set, so that a user can override the setting but the default is still there.

**Comment by MrMEEE** [comment]
I completely agree.. working on solving this.. got something on the way..

**Comment by MrMEEE** [comment]
Ok... just introduced ~/.ironhiderc

This file is persistant over updates, and also allows different users to have different ironhide settings...

Also, I added the ironhide-settings utility, which contain a lot different options from the ironhide configuration file and nvidia-settings...

Just uploaded the packages, so it should available soon...
