### ISSUE TITLE
Asus K93SV Error inserting nvidia_current

### ISSUE THREAD

**Issue by duxy** [MrMEEE/ironhide#147]
Used the following to enable/disable card:

enable: _SB.PCI0.PEG0.PEGP._ON
disable:_SB.PCI0.PEG0.PEGP._OFF

ironhide-configuration detection is not working on this.

error is:

<pre>
* Starting Ironhide X server ironhide                                          _ON Enabling nVidia card succeeded.
FATAL: Error inserting nvidia_current (/lib/modules/3.0.0-12-generic/updates/dkms/nvidia_current.ko): No such device
... * The nvidia driver was not loaded, try: sudo modprobe nvidia-current        * The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
ironhide could not be started - optirun cannot be executed.
</pre>

Xorg.8.log:

<pre>
[  1007.134] (EE) NVIDIA: Failed to load the NVIDIA kernel module. Please check 
your
[  1007.134] (EE) NVIDIA:     system's kernel log for additional error messages.
[  1007.134] (II) UnloadModule: "nvidia"
[  1007.134] (II) Unloading nvidia
[  1007.134] (EE) Failed to load module "nvidia" (module-specific error, 0)
</pre>

dmesg:

<pre>
[ 1006.454273] acpi_call: Calling \_SB.PCI0.PEG0.PEGP._ON
[ 1006.952172] acpi_call: Call successful: 0x0
[ 1007.026346] nvidia 0000:01:00.0: power state changed by ACPI to D0
[ 1007.026359] nvidia 0000:01:00.0: power state changed by ACPI to D0
[ 1007.026378] nvidia 0000:01:00.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
[ 1007.026397] nvidia 0000:01:00.0: setting latency timer to 64
[ 1007.026406] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=none,decodes=none:owns=none
[ 1007.045977] NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:0df4) installed
[ 1007.045978] NVRM: in this system is not supported by the 290.03 NVIDIA Linux
[ 1007.045980] NVRM: graphics driver release.  Please see 'Appendix A -
[ 1007.045981] NVRM: Supported NVIDIA GPU Products' in this release's README,
[ 1007.045983] NVRM: available on the Linux graphics driver download page at
[ 1007.045984] NVRM: www.nvidia.com.
[ 1007.045992] nvidia 0000:01:00.0: PCI INT A disabled
[ 1007.046001] nvidia: probe of 0000:01:00.0 failed with error -1
[ 1007.046021] NVRM: The NVIDIA probe routine failed for 1 device(s).
[ 1007.046023] NVRM: None of the NVIDIA graphics adapters were initialized!
</pre>

I would appreciate your help. Thanks.

**Comment by MDCore** [comment]
I'm getting the same problem with a clevo w170hn. After a reinstall of nvidia-current and ironhide I get the info below. The configuration doesn't work either, lots of errors and failures. 

command line:

```
$ optirun glxgears 
 * Starting Ironhide X server ironhide                                                                                                                                           _PS0 Enabling nVidia Card Succeded.
FATAL: Error inserting nvidia_current (/lib/modules/3.0.0-12-generic/updates/dkms/nvidia_current.ko): No such device
... * The nvidia driver was not loaded, try: sudo modprobe nvidia-current                                                                                                         * The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                                                 [fail] 
ironhide could not be started - optirun cannot be executed.
```

Syslog:

``` log
Nov 19 21:03:44 Frigate kernel: [ 5825.642959] acpi_call: Calling \_SB.PCI0.PEG0.PEGP._ON
Nov 19 21:03:44 Frigate kernel: [ 5825.913966] acpi_call: Call successful: 0xed
Nov 19 21:03:44 Frigate kernel: [ 5826.092651] nvidia 0000:01:00.0: power state changed by ACPI to D0
Nov 19 21:03:44 Frigate kernel: [ 5826.092664] nvidia 0000:01:00.0: power state changed by ACPI to D0
Nov 19 21:03:44 Frigate kernel: [ 5826.092674] nvidia 0000:01:00.0: enabling device (0006 -> 0007)
Nov 19 21:03:44 Frigate kernel: [ 5826.092689] nvidia 0000:01:00.0: PCI INT A -> GSI 16 (level, low) -> IRQ 16
Nov 19 21:03:44 Frigate kernel: [ 5826.092704] nvidia 0000:01:00.0: setting latency timer to 64
Nov 19 21:03:44 Frigate kernel: [ 5826.092714] vgaarb: device changed decodes: PCI:0000:01:00.0,olddecodes=none,decodes=none:owns=none
Nov 19 21:03:44 Frigate kernel: [ 5826.092794] NVRM: The NVIDIA GPU 0000:01:00.0 (PCI ID: 10de:0df4) installed
Nov 19 21:03:44 Frigate kernel: [ 5826.092797] NVRM: in this system is not supported by the 290.06 NVIDIA Linux
Nov 19 21:03:44 Frigate kernel: [ 5826.092799] NVRM: graphics driver release.  Please see 'Appendix A -
Nov 19 21:03:44 Frigate kernel: [ 5826.092801] NVRM: Supported NVIDIA GPU Products' in this release's README,
Nov 19 21:03:44 Frigate kernel: [ 5826.092803] NVRM: available on the Linux graphics driver download page at
Nov 19 21:03:44 Frigate kernel: [ 5826.092806] NVRM: www.nvidia.com.
Nov 19 21:03:44 Frigate kernel: [ 5826.092819] nvidia 0000:01:00.0: PCI INT A disabled
Nov 19 21:03:44 Frigate kernel: [ 5826.092835] nvidia: probe of 0000:01:00.0 failed with error -1
Nov 19 21:03:44 Frigate kernel: [ 5826.092879] NVRM: The NVIDIA probe routine failed for 1 device(s).
Nov 19 21:03:44 Frigate kernel: [ 5826.092883] NVRM: None of the NVIDIA graphics adapters were initialized!
```

**Comment by duxy** [comment]
works with bumblebee-3.0 & bbswitch
