### ISSUE TITLE
FATAL: Error inserting nvidia_current (Ubuntu 11.10)

### ISSUE THREAD

**Issue by iancboswell** [MrMEEE/ironhide#149]
I am having some issues getting Ironhide to stay working. After I (re)install it, it works great. However, after I restart the computer, it gives me this error when I try to run it:
- Starting Ironhide X server ironhide                                          ... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current        \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  ironhide could not be started - optirun cannot be executed.

I tried running sudo modprobe nvidia-current, and it gave me this:

FATAL: Error inserting nvidia_current (/lib/modules/3.0.0-12-generic/updates/dkms/nvidia-current.ko): No such device

I've tried running ironhide-configuration again, but all the tests failed. If I reinstall Ironhide, it works perfectly, but then after I reboot this happens again.

**Comment by iancboswell** [comment]
Just submitted ironhide-bugreport.

**Comment by lunderlini** [comment]
$sudo ironhide-settings

then change "Always enable the nVidia card before disabling" option to "No"
reboot and try again to work

**Comment by iancboswell** [comment]
It works! Thank you so much :)
