### ISSUE TITLE
not loading

### ISSUE THREAD

**Issue by avilella** [MrMEEE/ironhide#16]
It seems the ironhide installation went well, but the programs won't start. Optirun seems to correctly load the nvidia-current module, but the program won't start. Also, I have to manually call sudo ironhide-disablecard, otherwise calling _ON a second time with optirun locks the laptop.

avilella@magneto:~$ lsmod | grep nvi
avilella@magneto:~$ optirun google-chrome
- Starting Ironhide X server ironhide                                                                                                                                  _ON Enabling nVidia Card Succeded.
  .                                                                                                                                                                [ OK ]
  ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded: ignored.
  ERROR: ld.so: object 'librrfaker.so' from LD_PRELOAD cannot be preloaded: ignored.
- Stopping Ironhide X server ironhide                                                                                                                           [fail] 
  avilella@magneto:~$ sudo ironhide-disablecard
  _OFF Disabling nVidia Card Succeded.
  avilella@magneto:~$ optirun glxspheres
- Starting Ironhide X server ironhide                                                                                                                                  _ON Enabling nVidia Card Succeded.
  .                                                                                                                                                                [ OK ]
  Polygons in scene: 62464
- Stopping Ironhide X server ironhide                                                                                                                           [fail] 
  avilella@magneto:~$ sudo ironhide-disablecard
  _OFF Disabling nVidia Card Succeded.
  avilella@magneto:~$ sudo optirun glxspheres
- Starting Ironhide X server ironhide                                                                                                                                  _ON Enabling nVidia Card Succeded.
  .                                                                                                                                                                [ OK ]
  Polygons in scene: 62464
- Stopping Ironhide X server ironhide                                                                                                                           [fail]

**Comment by MrMEEE** [comment]
does glxgears work.. 

did the gears work in the configuration??

**Comment by avilella** [comment]
No, it doesn't work.

optirun glxgears
- Starting Ironhide X server ironhide                                                                                                                                  _ON Enabling nVidia Card Succeded.
  .                                                                                                                                                                [ OK ]
- Stopping Ironhide X server ironhide                                                                                                                           [fail] 
  avilella@magneto:~$

**Comment by avilella** [comment]
Found the solution, my laptop conf requires CRT-0, so I manually changed it in the ConnectedMonitor section in this file:
/etc/X11/xorg.conf.nvidia

**Comment by MrMEEE** [comment]
Ok.. could you please help me out here.. I don't get why I detect the wrong ConnectedMonitor...

Please try to run:

CONNECTEDMONITOR=`LD_LIBRARY_PATH=/usr/lib/nvidia-current /usr/lib/nvidia-current/bin/nvidia-xconfig --query-gpu-info

**Comment by MrMEEE** [comment]
You might need to run the enable script first...

**Comment by avilella** [comment]
avilella@magneto:~$
CONNECTEDMONITOR=`LD_LIBRARY_PATH=/usr/lib/nvidia-current
/usr/lib/nvidia-current/bin/nvidia-xconfig --query-gpu-info`
avilella@magneto:~$ echo $CONNECTEDMONITOR
Number of GPUs: 1 GPU #0: Name : GeForce 310M PCI BusID : PCI:1:0:0
Number of Display Devices: 0
avilella@magneto:~$

On Fri, Aug 26, 2011 at 2:29 PM, MrMEEE
reply@reply.github.com
wrote:

**Comment by MrMEEE** [comment]
Ok.. in the installation, where you asked which connectedmonitor to use???

**Comment by avilella** [comment]
Yes, I chose one randomly since I didn't know the answer.

On Fri, Aug 26, 2011 at 2:34 PM, MrMEEE
reply@reply.github.com
wrote:

**Comment by MrMEEE** [comment]
ok.. maybe I should make some more tests around that selection.. thanks for the feedback...
