### ISSUE TITLE
failed to load nvidia driver after reboot

### ISSUE THREAD

**Issue by vitk** [MrMEEE/ironhide#165]
everything looked to work fine before reboot. after that I always see the following error:
- Starting Ironhide X server ironhide                                          _ON Enabling nVidia card succeeded.
  FATAL: Error inserting nvidia_current (/lib/modules/3.0.0-12-generic/updates/dkms/nvidia_current.ko): No such device
  ... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current        \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  ironhide could not be started - optirun cannot be executed.

NOTE: nvidia card looks to be powered off when unplugged taking into account the battery life forecast.

**Comment by lunderlini** [comment]
the same as #149

**Comment by vitk** [comment]
just checked the solution proposed for #149. works for me too. thanks a lot for your great job!

**Comment by lunderlini** [comment]
I'm just a user sharing some experience~
