### ISSUE TITLE
ironhide installs but optirun fails to run

### ISSUE THREAD

**Issue by condefenring** [MrMEEE/ironhide#17]
Hi.
   I'm running ubuntu 11.10 in u33jc. I can change from one gpu to another using bios. when i boot up with linux
i only can see one gpu at the same time, i mean i boot in bios with intel card i only can see intel card with lspci and the same when i boot with nvidia.

  acpi_calls seems to work but no diference in battery rate in /proc/acpi/battery. that's mean bios block access to one of the GPU ???

do I need to do a bios update????

nvidia-current seems install correctly but when i execute bumblebee-enabled then module can not load correctly in the kernel.

**Comment by MrMEEE** [comment]
if you can't see both cards, neighter bumblebee nor ironhide will work...

You bios should be set to the intel card, so it becomes the primary... and then you should be able to see the nvidia card at the same time...

Please try to contact @avilella here on github.. maybe he has an acpi command to activate the nvidia card...

**Comment by avilella** [comment]
The u33jc has a BIOS "compatible" mode that will only show the nvidia card, mainly so pre-Win7 versions of Windows will work. The other mode should show both cards under Linux. Which mode are you using?

**Comment by condefenring** [comment]
Thanks.
I can load module acpi_call without problem and i get the string "IT works!" when i execute script   ./test_off.sh

so i'm not sure if the problem is in the "code" i send to the ACPI_CALL module.

acpi_call.ko

### To check that the status of your VGA devices, run this command:

```
lspci -vnnn | grep VGA
```

### Now run this script:

```
./test_off.sh
```

### If you see a "works!" messa

**Comment by condefenring** [comment]
Hello aviella thanks for joining us.
I've booted with both modes.
    1) Windows Compatible Mode (Or something like that) (This boots with intel)
    2) Others.  (This boots with nvidia).

In mode 1 i only see Intel in mode 2 i only see Nvidia.  My Ubuntu version is 11.10. kernel 3.0.9 I think.

**Comment by avilella** [comment]
you should see both with the compatible mode:

lspci | grep VGA
00:02.0 VGA compatible controller: Intel Corporation Core Processor
Integrated Graphics Controller (rev 18)
01:00.0 VGA compatible controller: nVidia Corporation GT218 [GeForce
310M](rev a2)

On Fri, Aug 26, 2011 at 4:42 PM, condefenring
reply@reply.github.com
wrote:

**Comment by condefenring** [comment]
I know i should see that  :) but i don't :).
Only this...
lspci | grep VGA 
00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 18)

Could you send me please your bios version??? what Linux distribution, kernel version do you have????

**Comment by avilella** [comment]
Ubuntu Natty.

uname -a
Linux magneto 2.6.38-11-generic-pae #48-Ubuntu SMP Fri Jul 29 20:51:21
UTC 2011 i686 i686 i386 GNU/Linux
avilella@magneto:~$
avilella@magneto:~$ sudo dmidecode -s system-version
[sudo] password for avilella:
1.0

If you still keep the Windows installed, one option is to boot under
Windows and then _shutdown_ normally under Windows, then reboot under
Linux. This should make sure the status of the nvidia card is correct
after Windows...

On Fri, Aug 26, 2011 at 4:52 PM, condefenring
reply@reply.github.com
wrote:

**Comment by condefenring** [comment]
Thats a problem i dont have windows. i will try to reinstall it and I will give you more info in a couple of days thanks anyway.

**Comment by avilella** [comment]
also try to call the same method _PS0 in linux and reboot.

echo '_SB.PCI0.PEG1.GFX0._PS0 > /proc/acpi/call

On Fri, Aug 26, 2011 at 5:16 PM, condefenring
reply@reply.github.com
wrote:

**Comment by condefenring** [comment]
Thanks for th fast answer but Tested and not working mmmhh. Sure the code is correct for U33JC???

**Comment by condefenring** [comment]
The EXACT bios Parameter is....

```
    Boot VGA Controller Selection For [WIndows 7/Vista]
                                                       [Others]
```

There is no Hybrid option. Are you sure is not a BIOS issue???.

**Comment by avilella** [comment]
I use Windows 7/Vista, which I believe is the hybrid option. The
Others should be the one that hides the intel card from the system...

On Fri, Aug 26, 2011 at 7:34 PM, condefenring
reply@reply.github.com
wrote:

**Comment by condefenring** [comment]
Thanks very much for the help, I reformatted root partition in order to make room for a windows 7 partition. After reinstalling i can see both GPU without problems in linux (Ubuntu 11.04) , Now i will check if ironhide projects works :) thanks very much for the help.
