### ISSUE TITLE
Installs fine, but doesn't work when I restart.

### ISSUE THREAD

**Issue by Pijuli** [MrMEEE/ironhide#180]
Ubuntu 11.10, gnome-shell, Asus A53S, GT540m
I installed all as it is explained. I rebooted. Tried glxgears with optirun and without and got 60fps and 700fps. Good.

Here it comes the problem. Next restart: is not working anymore. Optirun simply doesn't activate nvidia card. It doesn't bring up any error and when I activate, with ironhide-enable and disable with ironhide-disable, it works but with no change in fps. When I re-run glxgears with and without optirun I just get 60fps.

**Comment by Pijuli** [comment]
I managed to "make it work". When the laptop is unplugged from AC it WONT enable Nvidia. When you plug it into AC works like charm...

Anyway, thanks for the work and see if you can fix this.

Thanks.

**Comment by MrMEEE** [comment]
Hi... just go into ironhide-settings and disable "ECO Mode"

**Comment by Pijuli** [comment]
Hi... I'm sorry I didn't see that. Then thanks and great job.

If there is any way I can help the porject just tell me.

;)
