### ISSUE TITLE
ironhide-submitsystem Power Control Scripts

### ISSUE THREAD

**Issue by Ktl-XV** [MrMEEE/ironhide#21]
When submitting a profile with new Power Control Scripts, ironhide-submitsystem does not detect them.

I'll put them here anyway:
Toshiba Satelite A660
disable:
    echo '_SB.PCI0.PEG0.PEGP._OFF' > /proc/acpi/call
enable:
    echo '_SB.PCI0.PEG0.PEGP._ON' > /proc/acpi/call

Very good job, thanks

**Comment by MrMEEE** [comment]
Hi..

Thanks for the feedback..

Could you please try to submit again???

**Comment by Ktl-XV** [comment]
I believe the problem is in the ironhide-submitsystem, not in the web interface

Anyway, tried again and stayed the same:
http://img402.imageshack.us/img402/8620/screenshotironhidesubmi.png

Hope it helps

**Comment by MrMEEE** [comment]
could you please do:

cat /usr/local/bin/ironhide-enablecard

**Comment by MrMEEE** [comment]
Ok.. think I've fixed... please try ironhide~ubuntu21.. should be available soon...

**Comment by MrMEEE** [comment]
Could you please try again...??

**Comment by Ktl-XV** [comment]
Answering all questions

```
cat /usr/local/bin/ironhide-enablecard
#LOTS OF COMMENTED LINES
echo '\_SB.PCI0.PEG0.PEGP._ON' > /proc/acpi/call
```

Is isnt working jet ironhide~ubuntu23

**Comment by MrMEEE** [comment]
Still saying unavailable in version ~ubuntu23 ??????

could you please try:

diff /usr/local/bin/bumblebee-enablecard /usr/share/ironhide/examples/ironhide-enablecard.template

**Comment by Ktl-XV** [comment]
Found the bug
ironhide-configuration asks to create /usr/local/bin/_ironhide_-enablecard
and ironhide-submitsystem searches for /usr/local/bin/_bumblebee_-enablecard

**Comment by MrMEEE** [comment]
Great... Thanks...

Fixed in version ~ubuntu24
