### ISSUE TITLE
Dell L502X: Dedicated GPU runs in background

### ISSUE THREAD

**Issue by tamas-boczan** [MrMEEE/ironhide#216]
I'm on Dell L502X with GT540M and using Ubuntu 11.10 x64.
I'm using Marvin E Budd's configuration and IRONHIDE_ACPI_MODE is set to 0.
The system's using the Sandy Bridge GPU, but the discrete card is still running in background producing heat, noise and poor battery life.

**Comment by Lekensteyn** [comment]
This does not seem to be an Optimus laptop, unless I'm mistaken. For better power management support, see http://askubuntu.com/a/36936/6969

**Comment by tamas-boczan** [comment]
of course it's an Optimus laptop, mine has an NVidia GT540M and Intel Sandy Bridge (i7 2720). But thank you for the link, I'm already using the latest (3.0) Bumblebee, and it seems to work fine.

**Comment by Lekensteyn** [comment]
You may be correct, I'm mixing up machines (Dell L702X). If your issue is solved, hit the close button.

**Comment by tamas-boczan** [comment]
It is, installing the latest Bumblebee solves it.
