### ISSUE TITLE
RF511 initial test failed

### ISSUE THREAD

**Issue by Redvis** [MrMEEE/ironhide#219]
After instalation ironhide-configuration work without any errors, but after reboot I have:  "Initial test failed.." and "Power configuration test failed.."

There is a log:

[  1531.531] 
X.Org X Server 1.10.4
Release Date: 2011-08-19
[  1531.531] X Protocol Version 11, Revision 0
[  1531.531] Build Operating System: Linux 2.6.24-29-server x86_64 Ubuntu
[  1531.531] Current Operating System: Linux pjakubowski-RF511 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 14:56:25 UTC 2011 x86_64
[  1531.531] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-3.0.0-12-generic root=UUID=cd0c4cb4-4755-4b36-b84c-a6b550ad0727 ro quiet splash pcie_aspm=force i915.i915_enable_fbc=1 i915.lvds_downclock=1 vt.handoff=7
[  1531.531] Build Date: 19 October 2011  05:21:26AM
[  1531.531] xorg-server 2:1.10.4-1ubuntu4.2 (For technical support please see http://www.ubuntu.com/support) 
[  1531.531] Current version of pixman: 0.22.2
[  1531.531]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[  1531.531] Markers: (--) probed, (*_) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  1531.531](==) Log file: "/var/log/Xorg.8.log", Time: Wed Jan  4 21:10:31 2012
[  1531.531](++) Using config file: "/etc/X11/xorg.conf.nvidia"
[  1531.531](==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  1531.532](==) ServerLayout "Layout0"
[  1531.532](**) |-->Screen "Screen0" (0)
[  1531.532](**) |   |-->Monitor "Monitor0"
[  1531.533](**) |   |-->Device "Device0"
[  1531.533](**) Option "AutoAddDevices" "false"
[  1531.533](**) Not automatically adding devices
[  1531.533](==) Automatically enabling devices
[  1531.533](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[  1531.533]    Entry deleted from font path.
[  1531.533](WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[  1531.533]    Entry deleted from font path.
[  1531.533](WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[  1531.533]    Entry deleted from font path.
[  1531.533](WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[  1531.533]    Entry deleted from font path.
[  1531.533](WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[  1531.533]    Entry deleted from font path.
[  1531.533](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/Type1,
    /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,
    built-ins
[  1531.533](++) ModulePath set to "/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules"
[  1531.533](**) Extension "Composite" is enabled
[  1531.533](==) |-->Input Device "<default pointer>"
[  1531.533](==) |-->Input Device "<default keyboard>"
[  1531.533](==) The core pointer device wasn't specified explicitly in the layout.
    Using the default mouse configuration.
[  1531.533](==) The core keyboard device wasn't specified explicitly in the layout.
    Using the default keyboard configuration.
[  1531.533](II) Loader magic: 0x7e0220
[  1531.533](II) Module ABI versions:
[  1531.533]    X.Org ANSI C Emulation: 0.4
[  1531.533]    X.Org Video Driver: 10.0
[  1531.533]    X.Org XInput driver : 12.3
[  1531.533]    X.Org Server Extension : 5.0
[  1531.535](--) PCI:_(0:0:2:0) 8086:0116:144d:c0a5 rev 9, Mem @ 0xf5400000/4194304, 0xc0000000/268435456, I/O @ 0x0000e000/64
[  1531.535](--) PCI: (0:1:0:0) 10de:0df4:144d:c0a5 rev 161, Mem @ 0xf4000000/16777216, 0xd0000000/268435456, 0xe0000000/33554432, I/O @ 0x0000d000/128, BIOS @ 0x????????/524288
[  1531.535](II) Open ACPI successful (/var/run/acpid.socket)
[  1531.535](II) "extmod" will be loaded. This was enabled by default and also specified in the config file.
[  1531.535](II) "dbe" will be loaded. This was enabled by default and also specified in the config file.
[  1531.535](II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[  1531.535](II) "record" will be loaded. This was enabled by default and also specified in the config file.
[  1531.535](II) "dri" will be loaded by default.
[  1531.535](II) "dri2" will be loaded by default.
[  1531.535](II) LoadModule: "dbe"
[  1531.536](II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[  1531.536](II) Module dbe: vendor="X.Org Foundation"
[  1531.536]    compiled for 1.10.4, module version = 1.0.0
[  1531.536]    Module class: X.Org Server Extension
[  1531.536]    ABI class: X.Org Server Extension, version 5.0
[  1531.536](II) Loading extension DOUBLE-BUFFER
[  1531.536](II) LoadModule: "extmod"
[  1531.537](II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[  1531.537](II) Module extmod: vendor="X.Org Foundation"
[  1531.537]    compiled for 1.10.4, module version = 1.0.0
[  1531.537]    Module class: X.Org Server Extension
[  1531.537]    ABI class: X.Org Server Extension, version 5.0
[  1531.537](II) Loading extension MIT-SCREEN-SAVER
[  1531.537](II) Loading extension XFree86-VidModeExtension
[  1531.537](II) Loading extension XFree86-DGA
[  1531.537](II) Loading extension DPMS
[  1531.537](II) Loading extension XVideo
[  1531.537](II) Loading extension XVideo-MotionCompensation
[  1531.537](II) Loading extension X-Resource
[  1531.537](II) LoadModule: "glx"
[  1531.537](II) Loading /usr/lib/nvidia-current/xorg/libglx.so
[  1531.551](II) Module glx: vendor="NVIDIA Corporation"
[  1531.552]    compiled for 4.0.2, module version = 1.0.0
[  1531.552]    Module class: X.Org Server Extension
[  1531.552](II) NVIDIA GLX Module  290.10  Wed Nov 16 18:01:24 PST 2011
[  1531.552](II) Loading extension GLX
[  1531.552](II) LoadModule: "record"
[  1531.552](II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[  1531.552](II) Module record: vendor="X.Org Foundation"
[  1531.552]    compiled for 1.10.4, module version = 1.13.0
[  1531.552]    Module class: X.Org Server Extension
[  1531.552]    ABI class: X.Org Server Extension, version 5.0
[  1531.552](II) Loading extension RECORD
[  1531.552](II) LoadModule: "dri"
[  1531.552](II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[  1531.552](II) Module dri: vendor="X.Org Foundation"
[  1531.552]    compiled for 1.10.4, module version = 1.0.0
[  1531.552]    ABI class: X.Org Server Extension, version 5.0
[  1531.552](II) Loading extension XFree86-DRI
[  1531.552](II) LoadModule: "dri2"
[  1531.552](II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[  1531.552](II) Module dri2: vendor="X.Org Foundation"
[  1531.552]    compiled for 1.10.4, module version = 1.2.0
[  1531.552]    ABI class: X.Org Server Extension, version 5.0
[  1531.552](II) Loading extension DRI2
[  1531.552](II) LoadModule: "nvidia"
[  1531.552](II) Loading /usr/lib/nvidia-current/xorg/nvidia_drv.so
[  1531.553](II) Module nvidia: vendor="NVIDIA Corporation"
[  1531.553]    compiled for 4.0.2, module version = 1.0.0
[  1531.553]    Module class: X.Org Video Driver
[  1531.556](EE) NVIDIA: Failed to load the NVIDIA kernel module. Please check your
[  1531.556](EE) NVIDIA:     system's kernel log for additional error messages.
[  1531.556](II) UnloadModule: "nvidia"
[  1531.556](II) Unloading nvidia
[  1531.556](EE) Failed to load module "nvidia" (module-specific error, 0)
[  1531.556](II) LoadModule: "mouse"
[  1531.557](II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[  1531.557](II) Module mouse: vendor="X.Org Foundation"
[  1531.557]    compiled for 1.10.2.902, module version = 1.7.1
[  1531.557]    Module class: X.Org XInput Driver
[  1531.557]    ABI class: X.Org XInput driver, version 12.3
[  1531.557](II) LoadModule: "kbd"
[  1531.557](WW) Warning, couldn't open module kbd
[  1531.557](II) UnloadModule: "kbd"
[  1531.557](II) Unloading kbd
[  1531.557](EE) Failed to load module "kbd" (module does not exist, 0)
[  1531.557](EE) No drivers available.
[  1531.557] 
Fatal server error:
[  1531.557] no screens found
[  1531.557] 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[  1531.557] Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[  1531.557]

**Comment by Lekensteyn** [comment]
It sounds like Ironhide provided wrong ACPI calls.

Try Bumblebee as described in http://askubuntu.com/a/36936/6969 (for upgrading, see http://wiki.bumblebee-project.org/Upgrading-on-Ubuntu)

**Comment by Redvis** [comment]
Thank you very much! Bumblebee 3.0 works great for me
