### ISSUE TITLE
Problem after installation

### ISSUE THREAD

**Issue by lcamacho** [MrMEEE/ironhide#22]
Hi, 
after a successfull installation I try optirun64 firefox and it fails show me this output
- Starting Ironhide X server ironhide  
  _ON Enabling nVidia card succeeded.
  FATAL: Error inserting nvidia_current (/lib/modules/2.6.38-11-generic/updates/dkms/nvidia-current.ko): No such device
  ... \* The nvidia driver was not loaded, try: sudo modprobe nvidia-current        \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
  ironhide could not be started - optirun cannot be executed.

I try to load manually nvidia but the answer is the same its weird  I'm updating from old bumblebee to ironhide and never see this problem

**Comment by lcamacho** [comment]
After read this issue https://github.com/MrMEEE/ironhide/issues/18 and play with /ironhide-disablecard-on-powerup with just comment the enable card call everything works except if suspend then resume same issue so I have to comment the disable card call so my question is how to save energy at reboot or resume if this call is commented? I cant remember this happen with the old version of bumblebee

**Comment by MrMEEE** [comment]
Just uploaded new version to ppa.. please try that when its compiled.. and report back... thanks

**Comment by lcamacho** [comment]
Thanks for the quick response, I test the change on ironhide-disablecard-on-powerup and is working in booting, suspend/resume, hibernate/resume the only thing left is that when booting the nvidia card is not shutdown theres something you can do with that? 

Plus how I can send you my enable and disable card scripts?

**Comment by MrMEEE** [comment]
Ok.. just uploaded a new release, should also soon be available.. that should fix it..

You can submit your scripts with ironhide-submitsystem

**Comment by lcamacho** [comment]
Tested and everything is working as suppose, thanks for all your work.

**Comment by MrMEEE** [comment]
great... thanks for your feedback..
