### ISSUE TITLE
Initial tests failed on Samsun RC530 (GT540M)

### ISSUE THREAD

**Issue by asm0dey** [MrMEEE/ironhide#227]
Tried number of nvidia drivers from different repos and from nvidia site.
Mb working with some concrete version?

--Edit
Forgeot to say, that Im on Ubuntu 11.10

**Comment by Lekensteyn** [comment]
Try Bumblebee as described in http://askubuntu.com/a/36936/6969 (for upgrading, see http://wiki.bumblebee-project.org/Upgrading-on-Ubuntu)

Do not uninstall the driver from nvidia.com, you are badly breaking things. Recovery instructions are available in the askubuntu link before.

**Comment by asm0dey** [comment]
Thanks, works with bumblbee v.3
