### ISSUE TITLE
No Power Configuration

### ISSUE THREAD

**Issue by ashon-ikon** [MrMEEE/ironhide#23]
Asus U41sv

"No power-on/off configuration has been reported for your machine,
 please manually enter configuration in:

 /usr/local/bin/ironhide-enablecard and /usr/local/bin/ironhide-disablecard

 Some examples are available in /usr/share/doc/ironhide/."

'/usr/share/doc/ironhide/' is EMPTY no example for me to follow

**Comment by MrMEEE** [comment]
try to look in /usr/share/ironhide/examples..

I think there is some info I have to update...

Maybe @avilella can help here..
