### ISSUE TITLE
Yet another "Error inserting nvidia_current" etc.

### ISSUE THREAD

**Issue by notanimposter** [MrMEEE/ironhide#233]
I am running Ubuntu 11.10, although this also happened on Natty, Maverick, Linux Mint 11, Linux Mint 12, elementary OS Jupiter (Ubuntu Maverick). It's really pissing me off at this point.
After suspending, frequently, but not always, I get this:

```
\* Starting Ironhide X server ironhide                                          _ON Enabling nVidia card succeeded.
FATAL: Error inserting nvidia_current (/lib/modules/3.0.0-15-generic/updates/dkms/nvidia_current.ko): No such device
... * The nvidia driver was not loaded, try: sudo modprobe nvidia-current        * The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log[fail] 
ironhide could not be started - optirun cannot be executed.
```

Running

```
sudo modprobe nvidia-current
```

does the same. Changing the setting for always enable before disabling makes no difference. I am using an Alienware M11x R1 (although the scripts the configuration forced me to use are from an R2 if I remember correctly.
A reboot temporarily fixes the problem for me, although it always comes back. The test_off.sh from acpi_call doesn't succeed either. Reinstalling nvidia-current fixes it temporarily as well, although that might actually be the re-installation of some dependent package that is actually fixing it. I would really appreciate some help with this, as it seems like a bug that affects many people.

**Comment by Lekensteyn** [comment]
acpi_calls are deprecated with the release of bbswitch, use Bumblebee instead: https://wiki.ubuntu.com/Bumblebee

**Comment by notanimposter** [comment]
I'll try installing bumblebee instead. I had bumblebee before Ironhide, and it did the same thing, but it may have changed for all I know.

**Comment by notanimposter** [comment]
I have installed bumblebee. It seems okay at the moment. I will monitor it for a day or two. Thanks for your help.
