### ISSUE TITLE
optirun -c option not working [patch]

### ISSUE THREAD

**Issue by gaspo** [MrMEEE/ironhide#235]
Hi sorry for simplicity, dont have time now, just reporting -c option on optirun is not working. this is how o fix it:

/usr/bin/optirun line 68

VGL_COMPRESS=$arg

change to 

VGL_COMPRESS=$1

**Comment by Lekensteyn** [comment]
You're outdated, Bumblebee is more shiny http://bumblebee-project.org

**Comment by gaspo** [comment]
you're right . thank you.
