### ISSUE TITLE
Ironhide Xserver failed to start

### ISSUE THREAD

**Issue by BattleLlama** [MrMEEE/ironhide#24]
Installed Ironhide in Ubuntu 10.10 running on an Alienware M11x-R2.  During configuration it's reported that the Xserver fails to start.  A copy of the output of the configuration script can be found below.

sudo ironhide-configuration 
1
AUTO
NVOP Disabling nVidia Card Succeded.
_PS3 Disabling nVidia Card Succeded.
_PS0 Enabling nVidia Card Succeded.
- Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
- Stopping Ironhide X server ironhide                                   [fail] 
  NVOP Disabling nVidia Card Succeded.
  _PS3 Disabling nVidia Card Succeded.
- Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia Card Succeded.
  ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log                                                                             [fail] 
- Stopping Ironhide X server ironhide                                   [fail] 

When the Xorg.8.log is viewed it reports that it Failed to initialize the NVIDIA graphics device.  Looking at the dmesg output shows that it failed to copy vbios to system memory.

**Comment by MrMEEE** [comment]
Could you please run the ironhide-bugreport tool???

I think that this is because the "outdated" drivers in 10.10 is causing problem..

Could you update to xorg-edgers or x-updates???:

https://launchpad.net/~xorg-edgers/+archive/ppa

https://launchpad.net/~ubuntu-x-swat/+archive/x-updates

**Comment by BattleLlama** [comment]
Bugreport completed and submitted at time of initial report.  I updated to Xorg edgers and still had the same problem.  I haven't updated to 11.04 only out of laziness, I'll close this issue and update to 11.04 and try again.

Thanks for the prompt reply.
