### ISSUE TITLE
virtualgl oneric

### ISSUE THREAD

**Issue by denisiussion** [MrMEEE/ironhide#27]
there is not amd64 virtualgl package for oneric in the ppa :(
Cannot install ironhide from ppa for oneric amd64

**Comment by MrMEEE** [comment]
I know.. working on it.. have some weird dependencies problems.. seems to be a bug in launchpad...

**Comment by MrMEEE** [comment]
If you really want to, you should be able to download the natty package and install that...

**Comment by MrMEEE** [comment]
Oneiric packages are now available... :D
