### ISSUE TITLE
use nvidia developer driver for ironhide

### ISSUE THREAD

**Issue by spitzbubchen** [MrMEEE/ironhide#29]
After installing CUDA in natty together with devdriver_4.0_linux_64_270.41.19 the synaptic ironhide install wants to use the nvidia-current (version 270.41.06-0ubuntu1) driver. Will this work with my CUDA install? Can ironhide use the nvidia developer driver instead?

**Comment by spitzbubchen** [comment]
Went ahead with the nvida-current driver install and system is broken....

**Comment by MrMEEE** [comment]
it should be possible to get the dev driver working.. have you tried running ironhide-configuration after installing the driver???

**Comment by spitzbubchen** [comment]
I gave up on the nvidia developer driver and the default nvidia-current driver. Using .xorg x-swat nvidia-current did the trick! Here is what I did.

sudo add-apt-repository ppa:ubuntu-x-swat/x-updates
sudo add-apt-repository ppa:mj-casalogic/ironhide
sudo apt-get update
sudo apt-get install ironhide

#this downloads the newest nvidia-current driver from x-swat. 

#install CUDA dependencies and then CUDA
sudo apt-get install build-essential gcc-4.4 g++-4.4 libxi-dev libxmu-dev freeglut3-dev

#avoid using the nvidia development driver by creating the following system links to nvidia-current
sudo ln -s /usr/lib/nvidia-current/libcuda.so /usr/lib/libcuda.so
sudo ln -s /usr/lib/nvidia-current/libGL.so /usr/lib/libGL.so
sudo ln -s /usr/lib/nvidia-current/libcuda.so.1 /usr/lib/libcuda.so.1

#make CUDA
cd ~/NVIDIA_GPU_Computing_SDK/C
make

#use ironhide as
optirun bin/linux/release/fluidsGL

# One issue. There is currently no way NOT to choose a suggested system profile in the "The following system profile has been found/selected:" ironhide install window... Also I have no idea of what the ACPI settings are for my Qosmio X775 are... It would be nice if ironhide had some way to probe for these settings.

Otherwise you saved me from returning my laptop!! Thx!

**Comment by MrMEEE** [comment]
Thanks for your feedback.. I'll probably include your changes to ironhide soon...

in regards to the acpi problems, I haven't found a way to probe for the yet, but try to write to @avilella

**Comment by avilella** [comment]
Can you please post your DSDT info?

please submit your laptop's DSDT.dsl and SSDT tables as an attachment
to this bug report:

```
http://bugs.launchpad.net/bugs/752542
```

To compile your DSDT and SSDTs information, install if you haven't
already the acpidump and iasl tools:

```
sudo apt-get install acpidump iasl
```

### or

```
sudo yum install pmtools iasl
```

Then run the following commands on a bash terminal:

```
mkdir ~/acpiinfo ; cd ~/acpiinfo
sudo acpidump > acpidump.txt
# enter password
sudo acpixtract acpidump.txt
ls *.dat | while read i; do iasl -d "${i}"; done
pid=`sudo dmidecode -s system-product-name`
vid=`sudo dmidecode -s system-version`
name=${pid// /}.${vid// /}
mkdir "${name}" && cp *.dsl "${name}"/
tar czf "${name}.tar.gz" "${name}"/ && ls -l "$( pwd )/${name}".tar.gz
```

This will create a tar.gz file that you can attach to the bug report.

Finally, for posting the information in the bug report, you can check
the laptop and graphics card model identifiers with these commands:

```
sudo dmidecode -s system-product-name && sudo dmidecode -s system-version
lspci -vnnn | perl -lne 'print if /^\d+\:.+(\[\S+\:\S+\])/' | grep VGA
```

This information will allow the full development of hybrid graphics
features for Linux. Thanks for your help!
