### ISSUE TITLE
XPS15 initial tests fail.

### ISSUE THREAD

**Issue by RazvanGG** [MrMEEE/ironhide#31]
This is the log after i run ironhide-configuration

[   739.489] 
X.Org X Server 1.10.1
Release Date: 2011-04-15
[   739.490] X Protocol Version 11, Revision 0
[   739.490] Build Operating System: Linux 2.6.24-28-server x86_64 Ubuntu
[   739.490] Current Operating System: Linux ubuntu 2.6.38-11-generic #48-Ubuntu SMP Fri Jul 29 19:02:55 UTC 2011 x86_64
[   739.490] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.38-11-generic root=UUID=64F01A53F01A2BB4 loop=/ubuntu/disks/root.disk ro quiet splash
[   739.490] Build Date: 11 August 2011  03:43:05PM
[   739.490] xorg-server 2:1.10.1-1ubuntu1.2 (For technical support please see http://www.ubuntu.com/support) 
[   739.490] Current version of pixman: 0.20.2
[   739.490]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[   739.490] Markers: (--) probed, (*_) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   739.490](==) Log file: "/var/log/Xorg.8.log", Time: Tue Aug 30 04:41:03 2011
[   739.491](++) Using config file: "/etc/X11/xorg.conf.nvidia"
[   739.491](==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   739.492](==) ServerLayout "Layout0"
[   739.492](**) |-->Screen "Screen0" (0)
[   739.492](**) |   |-->Monitor "Monitor0"
[   739.492](**) |   |-->Device "Device0"
[   739.492](**) Option "AutoAddDevices" "false"
[   739.493](**) Not automatically adding devices
[   739.493](==) Automatically enabling devices
[   739.493](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   739.493]    Entry deleted from font path.
[   739.493](WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   739.493]    Entry deleted from font path.
[   739.493](WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   739.493]    Entry deleted from font path.
[   739.493](WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   739.493]    Entry deleted from font path.
[   739.493](WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   739.493]    Entry deleted from font path.
[   739.493](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/Type1,
    /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,
    built-ins
[   739.493](++) ModulePath set to "/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules"
[   739.493](**) Extension "Composite" is enabled
[   739.493](==) |-->Input Device "<default pointer>"
[   739.493](==) |-->Input Device "<default keyboard>"
[   739.493](==) The core pointer device wasn't specified explicitly in the layout.
    Using the default mouse configuration.
[   739.493](==) The core keyboard device wasn't specified explicitly in the layout.
    Using the default keyboard configuration.
[   739.493](II) Loader magic: 0x7e17e0
[   739.493](II) Module ABI versions:
[   739.493]    X.Org ANSI C Emulation: 0.4
[   739.493]    X.Org Video Driver: 10.0
[   739.493]    X.Org XInput driver : 12.3
[   739.493]    X.Org Server Extension : 5.0
[   739.496](--) PCI:_(0:0:2:0) 8086:0126:1028:050e rev 9, Mem @ 0xf1400000/4194304, 0xe0000000/268435456, I/O @ 0x00004000/64
[   739.496](--) PCI: (0:1:0:0) 10de:0df4:0000:0000 rev 161, Mem @ 0xf0000000/16777216, 0xc0000000/268435456, 0xd0000000/33554432, I/O @ 0x00003000/128, BIOS @ 0x????????/524288
[   739.496](II) Open ACPI successful (/var/run/acpid.socket)
[   739.496](II) "extmod" will be loaded. This was enabled by default and also specified in the config file.
[   739.496](II) "dbe" will be loaded. This was enabled by default and also specified in the config file.
[   739.496](II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[   739.496](II) "record" will be loaded. This was enabled by default and also specified in the config file.
[   739.496](II) "dri" will be loaded by default.
[   739.496](II) "dri2" will be loaded by default.
[   739.497](II) LoadModule: "dbe"
[   739.498](II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[   739.498](II) Module dbe: vendor="X.Org Foundation"
[   739.498]    compiled for 1.10.1, module version = 1.0.0
[   739.498]    Module class: X.Org Server Extension
[   739.498]    ABI class: X.Org Server Extension, version 5.0
[   739.498](II) Loading extension DOUBLE-BUFFER
[   739.498](II) LoadModule: "extmod"
[   739.499](II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[   739.499](II) Module extmod: vendor="X.Org Foundation"
[   739.499]    compiled for 1.10.1, module version = 1.0.0
[   739.499]    Module class: X.Org Server Extension
[   739.499]    ABI class: X.Org Server Extension, version 5.0
[   739.499](II) Loading extension MIT-SCREEN-SAVER
[   739.499](II) Loading extension XFree86-VidModeExtension
[   739.499](II) Loading extension XFree86-DGA
[   739.499](II) Loading extension DPMS
[   739.499](II) Loading extension XVideo
[   739.499](II) Loading extension XVideo-MotionCompensation
[   739.499](II) Loading extension X-Resource
[   739.499](II) LoadModule: "glx"
[   739.500](II) Loading /usr/lib/nvidia-current/xorg/libglx.so
[   739.505](II) Module glx: vendor="NVIDIA Corporation"
[   739.505]    compiled for 4.0.2, module version = 1.0.0
[   739.505]    Module class: X.Org Server Extension
[   739.505](II) NVIDIA GLX Module  270.41.06  Mon Apr 18 15:10:15 PDT 2011
[   739.505](II) Loading extension GLX
[   739.505](II) LoadModule: "record"
[   739.505](II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[   739.505](II) Module record: vendor="X.Org Foundation"
[   739.505]    compiled for 1.10.1, module version = 1.13.0
[   739.505]    Module class: X.Org Server Extension
[   739.505]    ABI class: X.Org Server Extension, version 5.0
[   739.506](II) Loading extension RECORD
[   739.506](II) LoadModule: "dri"
[   739.506](II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[   739.506](II) Module dri: vendor="X.Org Foundation"
[   739.506]    compiled for 1.10.1, module version = 1.0.0
[   739.506]    ABI class: X.Org Server Extension, version 5.0
[   739.506](II) Loading extension XFree86-DRI
[   739.506](II) LoadModule: "dri2"
[   739.506](II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[   739.506](II) Module dri2: vendor="X.Org Foundation"
[   739.506]    compiled for 1.10.1, module version = 1.2.0
[   739.506]    ABI class: X.Org Server Extension, version 5.0
[   739.506](II) Loading extension DRI2
[   739.506](II) LoadModule: "nvidia"
[   739.506](II) Loading /usr/lib/nvidia-current/xorg/nvidia_drv.so
[   739.506](II) Module nvidia: vendor="NVIDIA Corporation"
[   739.506]    compiled for 4.0.2, module version = 1.0.0
[   739.506]    Module class: X.Org Video Driver
[   739.510](EE) NVIDIA: Failed to load the NVIDIA kernel module. Please check your
[   739.510](EE) NVIDIA:     system's kernel log for additional error messages.
[   739.510](II) UnloadModule: "nvidia"
[   739.510](II) Unloading nvidia
[   739.510](EE) Failed to load module "nvidia" (module-specific error, 0)
[   739.510](II) LoadModule: "mouse"
[   739.510](II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[   739.510](II) Module mouse: vendor="X.Org Foundation"
[   739.510]    compiled for 1.9.99.902, module version = 1.6.99
[   739.510]    Module class: X.Org XInput Driver
[   739.510]    ABI class: X.Org XInput driver, version 12.3
[   739.510](II) LoadModule: "kbd"
[   739.511](WW) Warning, couldn't open module kbd
[   739.511](II) UnloadModule: "kbd"
[   739.511](II) Unloading kbd
[   739.511](EE) Failed to load module "kbd" (module does not exist, 0)
[   739.511](EE) No drivers available.
[   739.511] 
Fatal server error:
[   739.511] no screens found
[   739.511] 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[   739.511] Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[   739.511]

**Comment by MrMEEE** [comment]
please try:

modprobe nvidia

**Comment by MrMEEE** [comment]
sry:

modprobe nvidia-current

**Comment by RazvanGG** [comment]
FATAL: Error inserting nvidia_current (/lib/modules/2.6.38-11-generic/updates/dkms/nvidia-current.ko): No such device

**Comment by MrMEEE** [comment]
ok..

Did you come from bumblebee??? or is it the first time installing ironhide/bumblebee??

**Comment by RazvanGG** [comment]
first time installing ironhide/bumblebee. And yes I had bumblebee before.

**Comment by RazvanGG** [comment]
Is there any way I can check bumblebee is no longer in my system? If that is an issue

**Comment by RazvanGG** [comment]
I just updated nvidia-current and still no dice.

**Comment by MrMEEE** [comment]
ok... please try:

rm -rf /usr/local/bin/bumblebee*
rm -rf /usr/local/bin/ironhide*

reboot and rerun ironhide-configuration

**Comment by RazvanGG** [comment]
second time after power management check gears did not appear. Is that an issue or am I all set?

**Comment by MrMEEE** [comment]
this is a problem.. ironhide will probably not work..

**Comment by RazvanGG** [comment]
Quick Testing of Ironhide with power manangement seems ok, gears don't appear a second time.

1
AUTO
AUTO
Error: could not unload nvidia module, leaving card turned on
- Starting Ironhide X server ironhide                                   [ OK ] 
- Stopping Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
                                                                       [ OK ]
- Starting Ironhide X server ironhide                                          Ironhide hasn't been configured for power management, please run ironhide-configuration.
  .                                                                        [ OK ]
  Another ironhide powered application is running, keeping ironhide alive.
  Error: could not unload nvidia module, leaving card turned on
- Starting Ironhide X server ironhide                                   [ OK ] 
- Stopping Ironhide X server ironhide                                          NVOP Disabling nVidia Card failed (Error: AE_NOT_FOUND).
  _PS3 Disabling nVidia Card failed (Error: AE_NOT_FOUND).
                                                                       [ OK ]
- Starting Ironhide X server ironhide                                          _PS0 Enabling nVidia Card failed (Error: AE_NOT_FOUND).
  .                                                                        [ OK ]
  Another ironhide powered application is running, keeping ironhide alive.
  System start/stop links for /etc/init.d/ironhide already exist.
  Adding user raz to group ironhide

**Comment by RazvanGG** [comment]
Is there a way I can check that on the nvidia side everything is ok?

**Comment by MrMEEE** [comment]
apparently it seems like the power-configuration is wrong...

Could you please run ironhide-bugreport, and tell me which profile you chose in the configuration...

**Comment by RazvanGG** [comment]
Brad Heath configuration is the one I used. I ran bugreport and uploaded I guess the issue..

**Comment by MrMEEE** [comment]
There are now power configuration in Brad Heath's configuration...

Try "Marvin E Budd"'s instead, that's the one the most people are using..

**Comment by RazvanGG** [comment]
Reinstalled everything fresh, and used Marvin E Budd config, everything works ok. Thanks!
