### ISSUE TITLE
Command hints

### ISSUE THREAD

**Issue by Philipp15b** [MrMEEE/ironhide#39]
Hello,

It would be really helpful if you could do something like a manpage, because I often forget the ironhide commands and I cant find a list or something. For example, now I'm searching for the command to do the setup again :P

**Comment by falbarelli** [comment]
Hey actually you just have to write ironhide and then press the tab key so all the options show up ;)

**Comment by Philipp15b** [comment]
Oh,
didnt work for me the first time, but now suddlenly it works... Thanks :)
