### ISSUE TITLE
can't uninstall ironhide

### ISSUE THREAD

**Issue by falbarelli** [MrMEEE/ironhide#43]
Hi I can't uninstall ironhide at all, I've got ubuntu 11.04 with 3.0 kernel in order to improve the performances of the intel card.

When I do "sudo apt-get remove ironhide" I get

(Reading database ... 277507 files and directories currently installed.)
Removing ironhide ...
ON Enabling NVIDIA card succeeded.
/usr/local/bin/ironhide-enablecard: line 30:  2277 Killed                  modprobe nvidia-current
groupdel: group 'ironhide' does not exist
dpkg: error processing ironhide (--remove):
 subprocess installed post-removal script returned error exit status 6

and the package seems to be broken, moreover i'm not able to use the 3d of the intel card anymore (ubuntu doesn't boot in unity, but in classic mode)

**Comment by MrMEEE** [comment]
please try to update then uninstall...

**Comment by MrMEEE** [comment]
Should be fixed..
