### ISSUE TITLE
Everything works until I reboot.

### ISSUE THREAD

**Issue by sridel** [MrMEEE/ironhide#45]
Everything works until I reboot. Nvidia stops working on reboot.

**Comment by MrMEEE** [comment]
try running the ironhide-settings utility and change "Always enable the nVidia card before disabling" to 0/no... and the reboot

**Comment by sridel** [comment]
Let me start by saying that I appreciate all the work you are doing.

Unfortunately, changing "Always enable the nVidia card before
disabling" to 0/no... and then rebooting didn't help. I could still
run optirun glxgears however it would not do much better than ~60 FPS.

However, what did work was going into the settings/config file (not
sure what the correct terminology is) for Ironhide with
$ sudo gedit /etc/default/ironhide
and changing ECO Mode to zero since I was running on battery.

# ECO Mode

# 1 :   ECO mode active, do not run ironhide on battery power.

# 0 :   ECO mode disabled

ECO_MODE=0

I saved the file and I tried optirun glxgears again (without a reboot)
and I was back to getting ~600FPS.

I rebooted  to test for persistence and it still continued to work.

Now for the other interesting observations...... (my apologies if this
has already been discussed)

I wanted to test how it would react to the machine being put into
Suspend. Soon after waking up from suspend....

xxxxxxx@Ubuntu64:~$ optirun glxgears
- Starting Ironhide X server ironhide
       _ON Enabling nVidia card succeeded.
  FATAL: Error inserting nvidia_current
  (/lib/modules/2.6.38-11-generic/updates/dkms/nvidia-current.ko): No
  such device
  ... \* The nvidia driver was not loaded, try: sudo modprobe
  nvidia-current        \* The Ironhide Xserver failed to start. Please
  check /var/log/Xorg.8.log[fail]
  ironhide could not be started - optirun cannot be executed.

Fix was to simply reboot again. optirun glxgears once again gave me a
little over 600 FPS.

I tried the Suspend test after changing the setting "Always enable the
nVidia card before disabling" to 0/no and a reboot and got the same
result as before.

Some other interesting observations:

After another reboot to make Ironhide work again I made the following
observations...

xxxxxx@Ubuntu64:~$ optirun glxgears
- Starting Ironhide X server ironhide
       _ON Enabling nVidia card succeeded.
  .                                                                        [ OK ]
  4739 frames in 5.0 seconds = 947.666 FPS <-- note the bump in FPS from
  600's to 900's.
  4809 frames in 5.0 seconds = 961.717 FPS
  4879 frames in 5.0 seconds = 975.776 FPS
  4963 frames in 5.0 seconds = 992.517 FPS
  2961 frames in 5.0 seconds = 592.027 FPS <-- around this point I
  maximized the window with the gears. Is this an expected result?)
  469 frames in 5.0 seconds = 93.700 FPS <-- with some Chrome 3D
  experiments FPS goes down to 3. So far none above 40 FPS.
  469 frames in 5.0 seconds = 93.651 FPS
  459 frames in 5.0 seconds = 91.661 FPS
  444 frames in 5.0 seconds = 88.702 FPS
  494 frames in 5.0 seconds = 98.637 FPS
  422 frames in 5.0 seconds = 84.374 FPS
  412 frames in 5.0 seconds = 82.369 FPS
  478 frames in 5.0 seconds = 95.457 FPS
  426 frames in 5.0 seconds = 85.100 FPS
- Stopping Ironhide X server ironhide
       _OFF Disabling nVidia card succeeded.
                                                                       [ OK ]

Kicked off optirun again soon after the first run and this time I was
back to FPS in the 600's...

xxxxxxx@Ubuntu64:~$ optirun glxgears
- Starting Ironhide X server ironhide
       _ON Enabling nVidia card succeeded.
  .                                                                        [ OK ]
  3233 frames in 5.0 seconds = 646.448 FPS
  3238 frames in 5.0 seconds = 647.594 FPS
  2963 frames in 5.0 seconds = 592.440 FPS
  3080 frames in 5.0 seconds = 615.819 FPS
- Stopping Ironhide X server ironhide
       _OFF Disabling nVidia card succeeded.

Hope this helps...

On Fri, Sep 2, 2011 at 7:37 PM, MrMEEE
reply@reply.github.com
wrote:

**Comment by MrMEEE** [comment]
Please try to update to version -ubuntu35 .. it should be available within the hour.. made a bug...

**Comment by MrMEEE** [comment]
Please try -ubuntu37... should fix this bug..

Please reopen if problem persists.,..
