### ISSUE TITLE
issue m14x on 11.10 beta1

### ISSUE THREAD

**Issue by madmantm** [MrMEEE/ironhide#46]
i know ubuntu beta1 is beta, but still there's oneric packages for ironhide.

i trie the two offered configs for my m14x, one being fedora and the other one ubuntu 11.04 and they do not work.

what should i do?

**Comment by MrMEEE** [comment]
please run ironhide-bugreport

**Comment by madmantm** [comment]
You can close this comment, i got it to work correctly with bumblebee
project.

On Wed, Sep 7, 2011 at 5:20 PM, Martin Juhl <
reply@reply.github.com>wrote:

> please run ironhide-bugreport
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MrMEEE/ironhide/issues/46#issuecomment-2033850

## 

_Marc-Andr Meloche_
*
*
