### ISSUE TITLE
wine apps crash under multi-arch VirtualGL 

### ISSUE THREAD

**Issue by rockorequin** [MrMEEE/ironhide#51]
I've got VirtualGL version 2.2.90-1~oneiricubuntu8 and nvidia-current 280.13-0ubuntu2 installed on 64 bit oneiric, and wine consistently report crashes of apps like explorer.exe, wineboot.exe with the message "terminate called after throwing an instance of 'rrerror'".

Sometimes there's a backtrace:

```
0 0xf77b8430 __kernel_vsyscall+0x10() in [vdso].so
1 0xf73cdc4f gsignal+0x4e() in libc.so.6 (0x7c920f18)
2 0xf73d1175 abort+0x174() in libc.so.6 (0x7c920f18)
...
11 0xf771884d in librrfaker.so (+0xa084c) (0x0033f3bc)
12 0xf73d2831 in libc.so.6 (+0x32830) (0xf7515324)
13 0xf73d28bd exit+0x2c() in libc.so.6 (0x0033f4f0)
14 0x7ef8d828 NtTerminateProcess+0xb7(handle=0xffffffff, exit_code=0) [/home/rocko/src/wine-git/dlls/ntdll/process.c:63] in ntdll (0x0033f4f0)
```

and so it seems to be when the exe terminates. It doesn't stop the actual application (game, explorer.exe, whatever) from running, but makes lots of annoying 'The application X has crashed' popups appear.

Is this a known issue? Is it one that should be reported directly to VirtualGL? It is only happening in the multi-arch VirtualGL that I installed from the ironhide PPA.

**Comment by rockorequin** [comment]
Anyone?

ie I guess what I'm asking is are the modifications needed in virtualgl to support multiarch part of the upstream release, or were they applied by the ironhide project?

**Comment by rockorequin** [comment]
Actually, it's not just 32 bit wine apps that crash when closing. glxspheres also crashes when you close it. optirun reports:

terminate called after throwing an instance of 'rrerror'
/usr/bin/optirun: line 118: 13815 Aborted                 (core dumped) vglrun -c $VGL_COMPRESS -d $VGL_DISPLAY -ld "$VGL_DRIVER" "$@"

After the crash you have to manually kill the processes that are left over and shut down the nvidia card.

**Comment by MrMEEE** [comment]
I'll upgrade to oneiric very soon, and will look into it then..

**Comment by rockorequin** [comment]
I can't recommend upgrading right now. unity-compiz is pretty unstable, and gnome-shell isn't much better. It was much more stable at Beta1 than now :(

**Comment by rockorequin** [comment]
Fwiw, the compiz instability problems might have been caused by https://bugs.launchpad.net/ubuntu/+source/unity/+bug/847967. So far it seems much better now that I've disabled that setting (ie set /apps/compiz-1/plugins/unityshell/screen0/options/show_minimized_windows = false) and restarted unity.

**Comment by rockorequin** [comment]
I have reported this issue at: https://sourceforge.net/tracker/?func=detail&aid=3415497&group_id=117509&atid=678327

**Comment by rockorequin** [comment]
It is now fixed in the latest CVS.

**Comment by MrMEEE** [comment]
I have just uploaded virtualgl 2.2.99 to the repos.. building right now.. 

Could you please verify that it works, when it's done building???

**Comment by MrMEEE** [comment]
BTW. 2.2.99 is just a number I gave it.. contains newest CVS version..

**Comment by MrMEEE** [comment]
Packages are now available... please report back :D

**Comment by rockorequin** [comment]
It's all good now, the latest virtualgl package no longer crashes.
