### ISSUE TITLE
Asus 1215n - ironhide can't enable nvidia card ...

### ISSUE THREAD

**Issue by csaba2000** [MrMEEE/ironhide#53]
Ironhide can't turn on video card properly on an Asus EEE PC 1215n(bumblebee was installed previusly but got removed due to conflict)
Xorg.8.log: http://dl.dropbox.com/u/1536007/Xorg.8.log
EDIT: Bugreport sent with ironhide-bugreport.
EDIT: OS: ubuntu 11.04(natty)
Any help would be appreciated.

**Comment by csaba2000** [comment]
Looks like nvidia driver issue so far ...

**Comment by MrMEEE** [comment]
any nvidia errors in "dmesg"..

Have you tried changing the connected monitor to CRT-0 through the ironhide-settings tool??

**Comment by csaba2000** [comment]
will do a clean install incase of something was ***\* up. And will check those maybe I'll be lucky this time.
BTW: monitor not seems to be the problem bc I tried serval profiles with different and they had different connected monitor config but who knows maybe you are right. Will report back tomorow.

**Comment by csaba2000** [comment]
With fresh install it works but glxgears shows this and laggs like hell:
Xlib:  extension "NV-GLX" missing on display ":0.0".
Xlib:  extension "NV-GLX" missing on display ":0.0".
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
353 frames in 5.2 seconds = 67.932 FPS
320 frames in 5.3 seconds = 60.117 FPS

And there is a decrease of battery ...
EDIT: with optirun runs ok

**Comment by csaba2000** [comment]
Looks like nvidia package has a future to enable nvidia module by default (shows enabled in jockey-gtk) so need to disable it there ...

**Comment by csaba2000** [comment]
updated intel driver so bit better ...: Xlib:  extension "GLX" missing on display ":0.0".
Error: couldn't get an RGB, Double-buffered visual

**Comment by csaba2000** [comment]
after editing xorg.conf and fully updated driver all works ok;)
EDIT: rolled back nividia driver to 280.x

**Comment by brauliobo** [comment]
here I had to edit /etc/X11/xorg.conf.nvidia and change Option         "ConnectedMonitor" "CRT-0" to "DFP-0"
it worked!

thanks
