### ISSUE TITLE
Alienware M11x R3: Ironhide XServer failed to start

### ISSUE THREAD

**Issue by ghost** [MrMEEE/ironhide#56]
I just installed ironhide on my Alienware M11x R3 to get hybrid graphics working.
During configuration the following error was encountered: ... \* The Ironhide Xserver failed to start. Please check /var/log/Xorg.8.log

I tried installing new drivers from the xorg-edgers ppa, but this wouldn't help. This is my Xorg.8.log:

[    98.133] 
X.Org X Server 1.10.3.902 (1.10.4 RC 2)
Release Date: 2011-08-12
[    98.133] X Protocol Version 11, Revision 0
[    98.133] Build Operating System: Linux 2.6.24-29-xen x86_64 Ubuntu
[    98.133] Current Operating System: Linux ubuntu 2.6.38-11-generic #48-Ubuntu SMP Fri Jul 29 19:02:55 UTC 2011 x86_64
[    98.133] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-2.6.38-11-generic root=UUID=D4680CA3680C8708 loop=/ubuntu/disks/root.disk ro quiet splash
[    98.133] Build Date: 15 August 2011  03:52:57PM
[    98.133] xorg-server 2:1.10.3.902+git20110815+server-1.10-branch.4597f201-0ubuntu0sarvatt~natty (For technical support please see http://www.ubuntu.com/support) 
[    98.133] Current version of pixman: 0.21.8
[    98.133]    Before reporting problems, check http://wiki.x.org
    to make sure that you have the latest version.
[    98.133] Markers: (--) probed, (*_) from config file, (==) default setting,
    (++) from command line, (!!) notice, (II) informational,
    (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[    98.134](==) Log file: "/var/log/Xorg.8.log", Time: Mon Sep  5 16:52:12 2011
[    98.134](++) Using config file: "/etc/X11/xorg.conf.nvidia"
[    98.134](==) Using system config directory "/usr/share/X11/xorg.conf.d"
[    98.134](==) ServerLayout "Layout0"
[    98.134](**) |-->Screen "Screen0" (0)
[    98.134](**) |   |-->Monitor "Monitor0"
[    98.135](**) |   |-->Device "Device0"
[    98.135](**) Option "AutoAddDevices" "false"
[    98.135](**) Not automatically adding devices
[    98.135](==) Automatically enabling devices
[    98.135](WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[    98.135]    Entry deleted from font path.
[    98.135](WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[    98.135]    Entry deleted from font path.
[    98.135](WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[    98.135]    Entry deleted from font path.
[    98.135](WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[    98.135]    Entry deleted from font path.
[    98.135](WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[    98.135]    Entry deleted from font path.
[    98.135](==) FontPath set to:
    /usr/share/fonts/X11/misc,
    /usr/share/fonts/X11/Type1,
    /var/lib/defoma/x-ttcidfont-conf.d/dirs/TrueType,
    built-ins
[    98.135](++) ModulePath set to "/usr/lib/nvidia-current/xorg,/usr/lib/xorg/modules"
[    98.135](**) Extension "Composite" is enabled
[    98.135](==) |-->Input Device "<default pointer>"
[    98.135](==) |-->Input Device "<default keyboard>"
[    98.135](==) The core pointer device wasn't specified explicitly in the layout.
    Using the default mouse configuration.
[    98.135](==) The core keyboard device wasn't specified explicitly in the layout.
    Using the default keyboard configuration.
[    98.135](II) Loader magic: 0x7e3860
[    98.135](II) Module ABI versions:
[    98.135]    X.Org ANSI C Emulation: 0.4
[    98.135]    X.Org Video Driver: 10.0
[    98.135]    X.Org XInput driver : 12.3
[    98.136]    X.Org Server Extension : 5.0
[    98.137](--) PCI:_(0:0:2:0) 8086:0116:1028:04c8 rev 9, Mem @ 0xd1400000/4194304, 0xc0000000/268435456, I/O @ 0x00006000/64
[    98.137](--) PCI: (0:1:0:0) 10de:0df4:1028:04c8 rev 161, Mem @ 0xd0000000/16777216, 0xa0000000/268435456, 0xb0000000/33554432, I/O @ 0x00005000/128, BIOS @ 0x????????/524288
[    98.138](II) Open ACPI successful (/var/run/acpid.socket)
[    98.138](II) "extmod" will be loaded. This was enabled by default and also specified in the config file.
[    98.138](II) "dbe" will be loaded. This was enabled by default and also specified in the config file.
[    98.138](II) "glx" will be loaded. This was enabled by default and also specified in the config file.
[    98.138](II) "record" will be loaded. This was enabled by default and also specified in the config file.
[    98.138](II) "dri" will be loaded by default.
[    98.138](II) "dri2" will be loaded by default.
[    98.138](II) LoadModule: "dbe"
[    98.139](II) Loading /usr/lib/xorg/modules/extensions/libdbe.so
[    98.139](II) Module dbe: vendor="X.Org Foundation"
[    98.139]    compiled for 1.10.3.902, module version = 1.0.0
[    98.139]    Module class: X.Org Server Extension
[    98.139]    ABI class: X.Org Server Extension, version 5.0
[    98.139](II) Loading extension DOUBLE-BUFFER
[    98.139](II) LoadModule: "extmod"
[    98.139](II) Loading /usr/lib/xorg/modules/extensions/libextmod.so
[    98.140](II) Module extmod: vendor="X.Org Foundation"
[    98.140]    compiled for 1.10.3.902, module version = 1.0.0
[    98.140]    Module class: X.Org Server Extension
[    98.140]    ABI class: X.Org Server Extension, version 5.0
[    98.140](II) Loading extension MIT-SCREEN-SAVER
[    98.140](II) Loading extension XFree86-VidModeExtension
[    98.140](II) Loading extension XFree86-DGA
[    98.140](II) Loading extension DPMS
[    98.140](II) Loading extension XVideo
[    98.140](II) Loading extension XVideo-MotionCompensation
[    98.140](II) Loading extension X-Resource
[    98.140](II) LoadModule: "glx"
[    98.140](II) Loading /usr/lib/nvidia-current/xorg/libglx.so
[    98.147](II) Module glx: vendor="NVIDIA Corporation"
[    98.147]    compiled for 4.0.2, module version = 1.0.0
[    98.147]    Module class: X.Org Server Extension
[    98.147](II) NVIDIA GLX Module  285.03  Mon Aug 15 02:52:52 PDT 2011
[    98.147](II) Loading extension GLX
[    98.147](II) LoadModule: "record"
[    98.147](II) Loading /usr/lib/xorg/modules/extensions/librecord.so
[    98.147](II) Module record: vendor="X.Org Foundation"
[    98.147]    compiled for 1.10.3.902, module version = 1.13.0
[    98.147]    Module class: X.Org Server Extension
[    98.147]    ABI class: X.Org Server Extension, version 5.0
[    98.147](II) Loading extension RECORD
[    98.147](II) LoadModule: "dri"
[    98.147](II) Loading /usr/lib/xorg/modules/extensions/libdri.so
[    98.147](II) Module dri: vendor="X.Org Foundation"
[    98.147]    compiled for 1.10.3.902, module version = 1.0.0
[    98.147]    ABI class: X.Org Server Extension, version 5.0
[    98.147](II) Loading extension XFree86-DRI
[    98.147](II) LoadModule: "dri2"
[    98.148](II) Loading /usr/lib/xorg/modules/extensions/libdri2.so
[    98.148](II) Module dri2: vendor="X.Org Foundation"
[    98.148]    compiled for 1.10.3.902, module version = 1.2.0
[    98.148]    ABI class: X.Org Server Extension, version 5.0
[    98.148](II) Loading extension DRI2
[    98.148](II) LoadModule: "nvidia"
[    98.148](II) Loading /usr/lib/nvidia-current/xorg/nvidia_drv.so
[    98.148](II) Module nvidia: vendor="NVIDIA Corporation"
[    98.148]    compiled for 4.0.2, module version = 1.0.0
[    98.148]    Module class: X.Org Video Driver
[    98.148](II) LoadModule: "mouse"
[    98.148](II) Loading /usr/lib/xorg/modules/input/mouse_drv.so
[    98.148](II) Module mouse: vendor="X.Org Foundation"
[    98.148]    compiled for 1.10.2.902, module version = 1.7.1
[    98.148]    Module class: X.Org XInput Driver
[    98.148]    ABI class: X.Org XInput driver, version 12.3
[    98.148](II) LoadModule: "kbd"
[    98.149](WW) Warning, couldn't open module kbd
[    98.149](II) UnloadModule: "kbd"
[    98.149](II) Unloading kbd
[    98.149](EE) Failed to load module "kbd" (module does not exist, 0)
[    98.149](II) NVIDIA dlloader X Driver  285.03  Mon Aug 15 02:35:33 PDT 2011
[    98.149](II) NVIDIA Unified Driver for all Supported NVIDIA GPUs
[    98.149](--) using VT number 7

[    98.149](WW) xf86OpenConsole: setpgid failed: Operation not permitted
[    98.149](II) Loading sub module "fb"
[    98.149](II) LoadModule: "fb"
[    98.149](II) Loading /usr/lib/xorg/modules/libfb.so
[    98.149](II) Module fb: vendor="X.Org Foundation"
[    98.149]    compiled for 1.10.3.902, module version = 1.0.0
[    98.149]    ABI class: X.Org ANSI C Emulation, version 0.4
[    98.149](II) Loading sub module "wfb"
[    98.149](II) LoadModule: "wfb"
[    98.149](II) Loading /usr/lib/xorg/modules/libwfb.so
[    98.149](II) Module wfb: vendor="X.Org Foundation"
[    98.149]    compiled for 1.10.3.902, module version = 1.0.0
[    98.149]    ABI class: X.Org ANSI C Emulation, version 0.4
[    98.149](II) Loading sub module "ramdac"
[    98.149](II) LoadModule: "ramdac"
[    98.149](II) Module "ramdac" already built-in
[    98.149](II) Loading /usr/lib/nvidia-current/xorg/nvidia_drv.so
[    98.149](II) Loading /usr/lib/xorg/modules/libwfb.so
[    98.149](II) Loading /usr/lib/xorg/modules/libfb.so
[    98.149](**) NVIDIA(0): Depth 24, (--) framebuffer bpp 32
[    98.149](==) NVIDIA(0): RGB weight 888
[    98.149](==) NVIDIA(0): Default visual is TrueColor
[    98.149](==) NVIDIA(0): Using gamma correction (1.0, 1.0, 1.0)
[    98.149](**) NVIDIA(0): Option "ConnectedMonitor" "CRT-0"
[    98.149](**) NVIDIA(0): ConnectedMonitor string: "CRT-0"
[    98.335](WW) NVIDIA(GPU-0): Invalid ConnectedMonitor request; request was for 'CRT-0', but
[    98.335](WW) NVIDIA(GPU-0):     the valid display devices are 'DFP-0, DFP-1, DFP-2'.
[    98.338](II) NVIDIA(0): NVIDIA GPU GeForce GT 540M (GF108) at PCI:1:0:0 (GPU-0)
[    98.338](--) NVIDIA(0): Memory: 2097152 kBytes
[    98.338](--) NVIDIA(0): VideoBIOS: 70.08.4a.00.18
[    98.338](II) NVIDIA(0): Detected PCI Express Link width: 16X
[    98.338](--) NVIDIA(0): Interlaced video modes are supported on this GPU
[    98.338](--) NVIDIA(0): Connected display device(s) on GeForce GT 540M at PCI:1:0:0
[    98.338](--) NVIDIA(0):     none
[    98.343](EE) NVIDIA(0): No display devices found for this X screen.
[    98.365](II) UnloadModule: "nvidia"
[    98.365](II) Unloading nvidia
[    98.365](II) UnloadModule: "wfb"
[    98.365](II) Unloading wfb
[    98.365](II) UnloadModule: "fb"
[    98.365](II) Unloading fb
[    98.365](EE) Screen(s) found, but none have a usable configuration.
[    98.365] 
Fatal server error:
[    98.365] no screens found
[    98.365] 
Please consult the The X.Org Foundation support 
     at http://wiki.x.org
 for help. 
[    98.365] Please also check the log file at "/var/log/Xorg.8.log" for additional information.
[    98.365] 
[    98.365]  ddxSigGiveUp: Closing log

How can I get Ironhide to work correctly on my M11x R3?

**Comment by MrMEEE** [comment]
please use the nvidia-settings tool to change the connected monitor to "CRT-0"

**Comment by ghost** [comment]
I tried changing the connected monitor using the nvidia-settings tool, but running the tool gives me a message that I'm not using the Nvidia X Driver. After that the nvidia-settings tool does show, but I'm left with 4 basic options.
For some reason ironhide did work one time, but when it tried to run glxgears it failed because I didn't install the mesa-utils package. So I installed the package and tried again, but then it was back to the same error described above.

**Comment by hutch120** [comment]
Hi Guys,

I get around this error by running ironhide-settings instead of nvidia-settings. BUT it doesn't seem to be building a working xorg.conf.nvidia file. In fact when you try to save the settings it actually creates a file at xorg.conf (not xorg.conf.nvidia), I've tried both the merge option and overwrite. 

How does ironhide generate the xorg.conf.nvidia file?

Also, sorry, not trying to hijack this thread, but but just a bit more info, when I plug my external monitor it gets recognized by in the nvidia gui, but then my laptop monitor is not found so I can't seem to configure both external and laptop monitors, any ideas?

**Comment by ghost** [comment]
Hi hutch120,

I think you need to open a new issue for this, as it's completely different from my issue. I don't even have a working nvidia-settings tool, but I do have the xorg.conf.nvidia configuration file.

@MrMEEE I got ironhide to work during the first part of the configuration. It shows me the glxgears, but after that it can't start the ironhide XServer.

**Comment by Xqua** [comment]
Hi ! 

I have exactly the same issue ! 

Some people claims they succeeded in getting the R3 to work, but the Nvidia drivers don't even work ! 
And I don't know for you but I can't select the GPU in the BIOS which mean that I'm stuck with the Optimus settings ! 
So the fact that IronHide doesn't work is "normal" because the GPU is not selected (activated ?) In the bios and I (and I supose TheLuckys too because I have 100% similarity with him) should first try to get that working ! 

Is anybody knows how to get the Nvidia Driver to work on Linux (Ubuntu ?) for the R3 ! ??

Edit : 
Do you have the I7 R3 ???

Edit 2 : 
After a lot of looking on google, the R2 and R3 doesn't have the switch ! 

And also I got the acpi_call function to work I beleive ! 
I followed that : http://linux-hybrid-graphics.blogspot.com/2011/08/dell-alienware-m11xr3-release-3-linux.html

And I got that : 

xqua@Xqua-M11xR3:~/acpi_call$     lspci -vnnn | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

xqua@Xqua-M11xR3:~/acpi_call$ ./test_off.sh 
Trying _SB.PCI0.P0P1.VGA._OFF: failed
Trying _SB.PCI0.P0P2.VGA._OFF: failed
Trying _SB_.PCI0.OVGA.ATPX: failed
Trying _SB_.PCI0.OVGA.XTPX: failed
Trying _SB.PCI0.P0P3.PEGP._OFF: failed
Trying _SB.PCI0.P0P2.PEGP._OFF: failed
Trying _SB.PCI0.P0P1.PEGP._OFF: failed
Trying _SB.PCI0.MXR0.MXM0._OFF: failed
Trying _SB.PCI0.PEG1.GFX0._OFF: failed
Trying _SB.PCI0.PEG0.GFX0.DOFF: failed
Trying _SB.PCI0.PEG1.GFX0.DOFF: failed
Trying _SB.PCI0.PEG0.PEGP._OFF: works!

xqua@Xqua-M11xR3:~/acpi_call$     lspci -vnnn | grep VGA
00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev ff) (prog-if ff)

So that changed : 
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

to 

01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev ff) (prog-if ff)

**Comment by ghost** [comment]
Yes I have the i7 R3, and it doesn't have the switch because nVidia Optimus is very different from the system used in the M11x R1. The R1 had two separate videocards both connected to the display, but with nVidia Optimus only the Intel card is connected to the display.
I didn't try the acpicall method yet on my M11x, but it was buggy on my ASUS 1215N (also Optimus). For example, try putting the laptop in sleep mode when you've turned off the nVidia card. My 1215N used to crash when I tried that.

**Comment by Xqua** [comment]
Ok I got it to work with Bumblebee (not IronHide), so you guys might want to switch to bumbelbee !
