### ISSUE TITLE
Configuration errors on Dell XPS 15 running Ubuntu 11.10

### ISSUE THREAD

**Issue by ghost** [MrMEEE/ironhide#58]
When attempting to configure my Dell XPS 15 which is running Ubuntu 11.10 I have had repeated errors when I've been attempting to configure it. I have tried a few different configuration settings and none seem to be functioning correctly.

I will be submitting a bug report with the tool to support this ticket. More than happy to assist with issue diagnosis, please feel free to contact me via GitHub.

**Comment by MrMEEE** [comment]
does "dmesg" show any nvidia errors??

**Comment by web-dev** [comment]
The following is the dmesg output:

[   45.838902] usbcore: registered new interface driver usbhid
    [   45.838903] usbhid: USB HID core driver
    [  155.025298] usb 3-1: USB disconnect, device number 2
    [  650.161052] usb 3-1: new low speed USB device number 3 using xhci_hcd
    [  650.201281] xhci_hcd 0000:04:00.0: WARN: short transfer on control ep
    [  650.210269] xhci_hcd 0000:04:00.0: WARN: short transfer on control ep
    [  650.215275] xhci_hcd 0000:04:00.0: WARN: short transfer on control ep
    [  650.216489] usb 3-1: ep 0x81 - rounding interval to 64 microframes, ep desc says 80 microframes
    [  650.225232] xhci_hcd 0000:04:00.0: WARN: short transfer on control ep
    [  650.228212] xhci_hcd 0000:04:00.0: WARN: Stalled endpoint
    [  650.238616] input: Microsoft  Compact Optical Mouse 500 as /devices/pci0000:00/0000:00:1c.3/0000:04:00.0/usb3/3-1/3-1:1.0/input/input14
    [  650.238846] generic-usb 0003:045E:0737.0002: input,hidraw0: USB HID v1.11 Mouse [Microsoft  Compact Optical Mouse 500] on usb-0000:04:00.0-1/input0
    [  670.342591] usb 3-1: USB disconnect, device number 3
    [  947.628326] nvidia: module license 'NVIDIA' taints kernel.
    [  947.628335] Disabling lock debugging due to kernel taint
    [  947.977034] NVRM: The NVIDIA probe routine was not called for 1 device(s).
    [  947.977043] NVRM: This can occur when a driver such as nouveau, rivafb,
    [  947.977046] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
    [  947.977048] NVRM: the NVIDIA device(s).
    [  947.977054] NVRM: Try unloading the conflicting kernel module (and/or
    [  947.977056] NVRM: reconfigure your kernel without the conflicting
    [  947.977058] NVRM: driver(s)), then try loading the NVIDIA kernel module
    [  947.977061] NVRM: again.
    [  947.977065] NVRM: No NVIDIA graphics adapter probed!
    [  962.904464] acpi_call: Module loaded successfully
    [  962.909059] acpi_call: Calling _SB.PCI0.PEG0.PEGP._OFF
    [  963.166983] acpi_call: Call successful: 0x0
    [  963.202435] acpi_call: Calling _SB.PCI0.PEG0.PEGP._ON
    [  963.696573] acpi_call: Call successful: {0x00, 0x10, 0x00, 0xa1, 0x00, 0x00, 0x03, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf0, 0x0c, 0x00, 0x00, 0xc0, 0x00, 0x00, 0x00, 0x00, 0x0c, 0x00, 0x00, 0xd0, 0x00, 0x00, 0x00, 0x00, 0x01, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x28, 0x10, 0x0e, 0x05, 0x00, 0x00, 0x00, 0xf1, 0x60, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0b, 0x01, 0x00, 0x00, 0x28, 0x10, 0x0e, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xce, 0xd6, 0x23, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x68, 0x03, 0x00, 0x08, 0x00, 0x00, 0x00, 0x05, 0x78, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0xb4, 0x02, 0x00, 0xe0, 0x8d, 0x2c, 0x01, 0x10, 0x28, 0x00, 0x00, 0x02, 0x2d, 0x05, 0x00, 0x4a, 0x00, 0x02, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0NVRM: The NVIDIA probe routine was not called for 1 device(s).
    [  964.053412] NVRM: This can occur when a driver such as nouveau, rivafb,
    [  964.053413] NVRM: nvidiafb, or rivatv was loaded and obtained ownership of
    [  964.053414] NVRM: the NVIDIA device(s).
    [  964.053415] NVRM: Try unloading the conflicting kernel module (and/or
    [  964.053416] NVRM: reconfigure your kernel without the conflicting
    [  964.053416] NVRM: driver(s)), then try loading the NVIDIA kernel module
    [  964.053417] NVRM: again.
    [  964.053418] NVRM: No NVIDIA graphics adapter probed!

**Comment by web-dev** [comment]
This is probably some rookie mistake that i've made - should I be using a different driver or something?

**Comment by rockorequin** [comment]
Does it say on the command line that the nvidia module could not be loaded because the nvidia device is not present? If so, have a read of issue #84 - these two issues look the same to me. There's a configuration error for the XPS15 that prevents the nvidia card working after a reboot. There's also a simple fix for it.

**Comment by web-dev** [comment]
Thanks for your reply @rockrequin, I've had to switch back to windows because I couldn't get ubuntu to play nice with my system. I'll close this issue now.

**Comment by hanynowsky** [comment]
What a petty! So hasty!  I own the same laptop and things are working fine! Something went wrong during installation of IronHide! 
web-dev! You should wait for ironhide/bumblebee with stable GUi to be released.

**Comment by web-dev** [comment]
You're right about the hasty part! I've actually switched back to Ubuntu because I couldn't get anything done. I've tried to install Ironhide again, but I still got some errors during configuration. It did seem to activate the GPU though, because VMware viewer is behaving better now.

**Comment by hanynowsky** [comment]
Hum!! Virtuallization!! That's another story though! I still did not try it along with ironhide/bumblebee to give you hints.
Yet, if you can activate your GPU then it's a great step.
I compared your dmesg output with mine and yours shows that nvidia module was not loaded correctly or not loaded at all. But since you can activate your GPU now, I guess the problem now has disappeared.
I ll keep you informed once I use virtual machines.
Anyway, have you tried also with BUMBLEBEE PROJECT ?
