### ISSUE TITLE
Does ironhide install /etc/X11/xorg.conf.nvidia?

### ISSUE THREAD

**Issue by rockorequin** [MrMEEE/ironhide#61]
I've installed it in both natty and oneiric, and both times ironhide failed to start because the xorg.conf.nvidia file was missing. After copying an old version across, ironhide works correctly.

**Comment by MrMEEE** [comment]
Could you please try:

aptitude remove ironhide

dpkg --purge ironhide

aptitude install ironhide

and confirm that file isn't there..??

Here it installs with the package...

**Comment by rockorequin** [comment]
If I try the aptitude remove command, it wants to remove a bunch of stuff, like libxrender1, libxv1, libstdc++6, libqtcore4, libasound2, libc6, libfreetype6, libgcc1... that looks dangerous to me!

**Comment by rockorequin** [comment]
I purged it using synaptic and then rebooted and then reinstalled and /etc/X11/xorg.conf.nvidia _is_ being installed. I'm now getting the 'device not present' message, but that's a separate issue so I'll close this one.
