### ISSUE TITLE
Segmentation fault when executing program with opengl 3 context

### ISSUE THREAD

**Issue by marcelomp** [MrMEEE/ironhide#69]
When i run optirun ./tut1 on the executable compiled from source tut1.cpp a segmentation fault error occur i posted the error on arch linux forums https://bbs.archlinux.org/viewtopic.php?id=126068

Distro: Arch Linux release 2011.08.19
Kernel: 3.0-ARCH

baseboard-manufacturer  : Quanta
baseboard-product-name  : QLH  
baseboard-version       : TBD
system-manufacturer     : LG Electronics
system-product-name     : A520-P.BE51P1
system-version          : TBD

bumblebee: 2.3.2-1

**Comment by MrMEEE** [comment]
This github is for Ironhide only... not bumblebee..

Please report this at: https://github.com/Bumblebee-Project

or try ironhide instead:

https://launchpad.net/~mj-casalogic/+archive/ironhide/+packages
