### ISSUE TITLE
HOWTO: Install?

### ISSUE THREAD

**Issue by cement-head** [MrMEEE/ironhide#74]
Hello,

  How do I install Ironside?  I've added the PPA.  Do I first install the packages, reboot, enter into my BIOS and enable Optimus?

Thanks

**Comment by MrMEEE** [comment]
Just start by enabling optimus..

After adding the ppa:

sudo apt-get install ironhide

if the configuration is not run automatically, run the ironhide-configuration tool.. then everything should work

**Comment by cement-head** [comment]
Hi,

   If I reboot and enter the BIOS and then enable Optimus and then boot my machine - I get only a command line prompt.

   Q: Should I enable the PPA and install the packages BEFORE rebooting and enabling Optimus in the BIOS?

Thanks,
AJK

**Comment by Xqua** [comment]
It is because you probably don't have the GPU drivers installed ! You should install them on your system before you turn the GPU ON. 

Or you can also install them from the command line ! 

Don'f forget to backup your Xorg.conf files !!! Or you might not be able to go back if some problems happen !
