### ISSUE TITLE
glxgears didn't show up

### ISSUE THREAD

**Issue by Vanuan** [MrMEEE/ironhide#8]
I'm running ironhide-configure and having problems with glxgears step.
Initial configuration seems ok. But glxgears don't show up.

My /etc/X11/xorg.conf.nvidia:

https://gist.github.com/1169025

My /var/log/Xorg.8.log:

https://gist.github.com/1169031

What additional information should I provide?

**Comment by MrMEEE** [comment]
Do you get any errors?

Could you please try 

optirun glxgears 

and post the output

**Comment by Vanuan** [comment]
Unfortunately I don't have my laptop right now. But I remember there was a problem with stopping X server ([fail]). Something like:

```
Starting Ironhide X server [ok]

[my video card information]

Stopping Ironhide X server [fail]
```

Besides, I've installed bumblebee and it just works. So, I think I'll give up trying ironhide for some time.
Thanks.
