### ISSUE TITLE
Alienware m11x r3 i5 2537 nv gt540m

### ISSUE THREAD

**Issue by Pirate2011** [MrMEEE/ironhide#86]
seems to have the same issues than #56... 
cann't load ironhide xserver...
..
Plus I tried AlienFx Lite (a interesting software), it seems that Dell changed parts in hardware... for exemple when I do in a terminal "lsusb" command, I got:
....  187c : 522   Alienware Corporation  
( netbook BIOS verion A04 )

A little bit older netbook m11x r3 seems to have  187c : 516

**Comment by Camelcase** [comment]
I can confirm this, I've got the i7 version, same Problem.

**Comment by Xqua** [comment]
Hum I do have the i7 too ! 

Do you too have no BIOS Options for the GPU (Dicrete ?) !

**Comment by Camelcase** [comment]
Yes, no option to change the GPU whatsoever in the BIOS. This is actually not really bothering me since the machine seems to run on the intel by default. Though it would be nice to be able to change it. 
What is bothering me is that right now the intel seems unable to use the displayport :-( 
So I hope I could use the nvidia to do that. 
I think I got the same board revision as Pirate2011. It gives me the 522 on lsusb too.

**Comment by Pirate2011** [comment]
I confirm that I don't have any options for GPU in the BIOS.
Do someone tryied to flash the BIOS to another version to check if it can help Ironhide working?
My BIOS version is A04.

**Comment by Xqua** [comment]
No it's not possible anymore, but it's because of a new Optimus version ! ...

I got it working with the Bumbelee project ! https://github.com/Bumblebee-Project
Which is a Fork departed from the original Bumbelee Project ! 

I recommend you try it ! It worked for me !

**Comment by Pirate2011** [comment]
Many Thanks to Xqua!
Bumblebee work on my m11x r3... 
I followed this page for install : 
https://launchpad.net/~bumblebee/+archive/stable
Now I will check battery life with it.

For ACPI call, I can't do better than http://linux-hybrid-graphics.blogspot.com/
so far only off mode...

a) acpi_call
    sudo apt-get install git
    # type password
    git clone https://github.com/mkottman/acpi_call.git
    cd acpi_call
    make
    sudo insmod acpi_call.ko
To check that the status of your VGA devices, run this command:
    lspci -vnnn | grep VGA
Now run this script:
    ./test_off.sh

Nvidia's card seems to be off, and full battery can run a little more than 6 hours...

**Comment by Xqua** [comment]
Hey Pirate, if you suceed getting the ACPI calls to work can you please post something (or email me) the calls ? 

Cause I couldn't get it to work completely !

**Comment by Camelcase** [comment]
Awesome, thanks guys, with bumblebee(thx Xqua) and Pirate2011's ACPI Hint I can get most things working as I'd like to, the only thing missing would be the external display port(s). Does anyone have any luck with those by any chance (any idea is welcome) ?

**Comment by Pirate2011** [comment]
Ok I found a way to enable the GPU nvidia... on my m11x r3

to power off, read my last comment with ./test_off.sh

to power on, I modified the scipt test_off.sh
with (other test off ligns are useless)
_SB.PCI0.PEG0.PEGP._ON

then saved as
 test_on.sh
 and you have a script for power on... but I still need optirun to lunch software with the nvidia...

**Comment by Xqua** [comment]
does that worked for you ? the power on ? because I tried it and I just could wake up mu CGU at all ... (I needed to boot on a liveCD to reset the ACPI calls ...) 

can you just post the lspci before ./test_off and after and then /test_on ?

Thx !

**Comment by Pirate2011** [comment]
Note that I have two scripts :  test_off.sh  & test_on.sh
Here we go!

Nvidia is on...
lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

~/acpi_call $ sh ./test_off.sh

Trying _SB.PCI0.P0P1.VGA._OFF: failed
Trying _SB.PCI0.P0P2.VGA._OFF: failed
Trying _SB_.PCI0.OVGA.ATPX: failed
Trying _SB_.PCI0.OVGA.XTPX: failed
Trying _SB.PCI0.P0P3.PEGP._OFF: failed
Trying _SB.PCI0.P0P2.PEGP._OFF: failed
Trying _SB.PCI0.P0P1.PEGP._OFF: failed
Trying _SB.PCI0.MXR0.MXM0._OFF: failed
Trying _SB.PCI0.PEG1.GFX0._OFF: failed
Trying _SB.PCI0.PEG0.GFX0.DOFF: failed
Trying _SB.PCI0.PEG1.GFX0.DOFF: failed
Trying _SB.PCI0.PEG0.PEGP._OFF: works!

Nvidia is off...
~/acpi_call $ lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev ff) (prog-if ff)

~/acpi_call $ sh ./test_on.sh

Trying _SB.PCI0.PEG0.PEGP._ON: works!

Again Nvidia is on...
~/acpi_call $ lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

---

...I find to use directly acpi

 lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

~/acpi_call $ echo '_SB.PCI0.PEG0.PEGP._OFF' > /proc/acpi/call

~/acpi_call $ lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev ff) (prog-if ff)

~/acpi_call $ echo '_SB.PCI0.PEG0.PEGP._ON' > /proc/acpi/call

~/acpi_call $ lspci -vnnn | grep VGA

00:02.0 VGA compatible controller [0300]: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller [8086:0116](rev 09) (prog-if 00 [VGA controller])
01:00.0 VGA compatible controller [0300]: nVidia Corporation Device [10de:0df4](rev a1) (prog-if 00 [VGA controller])

---

Anyway we are speaking about bumblebee, so should we continue on this page? Because it's ironhide issues'pages, insn't it?

**Comment by Xqua** [comment]
OK ! It is working ! 
Thanks Pirate ! 
I don't know why but when I tried it (exactly the same as you ...) it crashed my ACPI and I had to reset them all ...
Anyway now it is working ! :D 

Here is a small script I made to check the battery rate ! 

The big spike is : optirun glxsphere
the small spike ... I don't know XD 
Values are in Mw

http://img43.imageshack.us/img43/2265/batteryu.png

BTW we should close this issue !

**Comment by Pirate2011** [comment]
I could not get Ironhide working... but few experiences were good.

Keep up the good work!
