### ISSUE TITLE
ironhide on asus 1215N doesn't work

### ISSUE THREAD

**Issue by antoniobove** [MrMEEE/ironhide#87]
I'm Italian so, sorry for my english.
fresh installation of ubuntu natty.
first step: installation of ironhide
second step: installation of nvidia driver (using ubuntu tool) and reboot
third step: run ironhide-configuration: glxgears doesn't start, using all the config.
the error is: Error: couldn't get an RGB, Double-buffered visual
what I have to do???

**Comment by csaba2000** [comment]
try: 2 commands and tell us if they work.(if it works you can stop it by CRTL + C
optirun glxgears
glxgears
would you post those config files from your sytem?
/usr/local/bin/ironhide-enablecard
/usr/local/bin/ironhide-disablecard
/etc/X11/xorg.conf
/etc/X11/xorg.conf.nvidia

and check if with program Additional drivers(jockey-gtk) say if nvidia card activated(if not activated do not activate then) ...

**Comment by antoniobove** [comment]
optirun glxgears doesn't work
glxgears runs at 60 FPS
ironhide-enablecard:
#!/bin/bash
#based on Pete Eberlein's asus1215n.sh script
#modified by Csaba Szobonya(csaba2@citromail.hu)
modprobe acpi_call
if ! lsmod | grep -q acpi_call; then
echo "Error: acpi_call module not loaded"
    exit
fi

acpi_call () {
    echo "$*" > /proc/acpi/call
    cat /proc/acpi/call
}
echo _PS0 $(acpi_call "_SB.PCI0.P0P4.GFX0._PS0")

#echo _PS0 $(acpi_call "_SB.PCI0.P0P4.GFX0._PS0")
echo P3MO $(acpi_call "_SB.PCI0.P0P4.GFX0.P3MO")
echo DGPS $(acpi_call "_SB.PCI0.P0P4.GFX0.DGPS")
#PSC=$(acpi_call "_SB.PCI0.P0P4.GFX0._PSC")
#echo _PSC ${PSC}
modprobe nvidia-current

ironhide-disablecard:
#!/bin/bash
#based on Pete Eberlein's asus1215n.sh script
#modified by Csaba Szobonya(csaba2@citromail.hu)

modprobe acpi_call
if ! lsmod | grep -q acpi_call; then
echo "Error: acpi_call module not loaded"
    exit
fi

acpi_call () {
    echo "$*" > /proc/acpi/call
    cat /proc/acpi/call
}

#echo _PS0 $(acpi_call "_SB.PCI0.P0P4.GFX0._PS0")
#echo P3MO $(acpi_call "_SB.PCI0.P0P4.GFX0.P3MO")
#echo DGPS $(acpi_call "_SB.PCI0.P0P4.GFX0.DGPS")
echo _DSM $(acpi_call "_SB.PCI0.P0P4.GFX0._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x1A {0x1,0x0,0x0,0x3}")

# acpi_call returns :

# Buffer {0x59 0x0 0x0 0x11} : card ready to turn off

# Buffer {0x41 0x0 0x0 0x11} : card already off

echo _PS3 $(acpi_call "_SB.PCI0.P0P4.GFX0._PS3")

PSC=$(acpi_call "_SB.PCI0.P0P4.GFX0._PSC")
echo _PSC ${PSC}
case "$PSC" in
0x0)
    PSC="on"
    echo "Error: acpi_call failed..."
    echo "Leaving nvidia card turned on!"
;;
0x3)
rmmod nvidia
if lsmod | grep -q nvidia; then
echo "Error: could not unload nvidia module, leaving card turned on"
exit
fi

;;
esac

/etc/X11/xorg.conf doesn't exist

/etc/X11/xorg.conf.nvidia:
Section "DRI"
    Mode 0666
EndSection

Section "ServerLayout"
    Identifier     "Layout0"
    Screen         "Screen0"
    Option         "AutoAddDevices" "false"
EndSection

Section "Module"
    Load  "dbe"
    Load  "extmod"
    Load  "glx"
    Load  "record"
    Load  "freetype"
    Load  "type1"
EndSection

Section "Files"
EndSection

Section "Device"
    Identifier     "Device0"
    Driver         "nvidia"
    VendorName     "NVIDIA Corporation"
    BusID          "PCI:04:00:0"
    Option         "IgnoreEDID"
    Option         "ConnectedMonitor" "DFP-0"
EndSection

Section "Screen"
    Identifier     "Screen0"
    Device         "Device0"
    Monitor        "Monitor0"
    DefaultDepth    24
    SubSection     "Display"
        Depth       24
        Modes      "1920x1200" "1920x1080" "1680x1050" "1600x1200" "1440x900" "1280x1024" "1366x768" "1360x768" "1280x800" "1024x768" "800x600" "640x480"
    EndSubSection
EndSection

Section "Extensions"
    Option "Composite" "Enable"
EndSection

Section "Monitor"
    Identifier     "Monitor0"
    VendorName     "Unknown"
    ModelName      "Unknown"
    HorizSync       28.0 - 73.0
    VertRefresh     43.0 - 72.0
    Option         "DPMS"
    Modeline       "1920x1200"  193.25  1920 2056 2256 2592  1200 1203 1209 1245 -hsync +vsync
    Modeline       "1920x1080"  173.00  1920 2048 2248 2576  1080 1083 1088 1120 -hsync +vsync
    Modeline       "1680x1050"  146.25  1680 1784 1960 2240  1050 1053 1059 1089 -hsync +vsync
    Modeline       "1600x1200"  161.00  1600 1712 1880 2160  1200 1203 1207 1245 -hsync +vsync
    Modeline       "1440x900"  106.50  1440 1528 1672 1904  900 903 909 934 -hsync +vsync
    Modeline       "1366x768"   85.25  1366 1440 1576 1784  768 771 781 798 -hsync +vsync
    Modeline       "1280x800"   83.50  1280 1352 1480 1680  800 803 809 831 -hsync +vsync
    Modeline       "1280x1024"  109.00  1280 1368 1496 1712  1024 1027 1034 1063 -hsync +vsync
EndSection

nvidia driver is not activated

**Comment by csaba2000** [comment]
The thing that might cause this is the missing xorg.conf file...
I had smilar issue before so I'll make a dummy xorg.conf file then and test with it.
btw: the ironhide-enablecard/disable card seems familiar to me maybe because its made by me;P

**Comment by csaba2000** [comment]
A fast test without xorg.conf file and same result as you.
btw: as I remember I had the same issue before and made an xorg.conf file.
So I'll link mine for a quick test.
To test it without restart:
open a console:
cd /etc/X11/
sudo wget http://dl.dropbox.com/u/1536007/ironhide/xorg.conf # will askfor your password

save all your app data as xserver will be restarted.
CTRL + ALT + F1
type your username and password
then use this command:
sudo service gdm restart # will ask your password again

now you are at the login screen from now you will know what to do;P

to test things try: optirun glxgears
glxgears

Don't forget to report back if it works;)

**Comment by antoniobove** [comment]
it seems to be working
glxgears: 60 fps (monitor refresh rate)
optirun glxgears: about 235 fps... is it a good value???

**Comment by csaba2000** [comment]
yeah thats good I get smilar results too;)
but you should check it with wine and a game;P
That will confirm it for sure...

**Comment by antoniobove** [comment]
uhm... games???
I prefer to use the PS3 for gaming...
It's worth a shot just for knowing...
thanks for all...!
