### ISSUE TITLE
Installation instructions?

### ISSUE THREAD

**Issue by avilella** [MrMEEE/ironhide#9]
This is what I've added to the blog page and the launchpad pages. Please let me know if the ironhide instructions are correct:
### For ironhide (Ubuntu Natty instructions):

```
sudo apt-add-repository ppa:mj-casalogic/ironhide
sudo apt-get update && sudo apt-get install ironhide
```
### For bumblebee (git installation):

```
sudo apt-get install git
# type password
git clone http://github.com/MrMEEE/bumblebee.git
cd bumblebee/
sudo ./install.sh
```
### report the FPS values on the mailing list:

```
optirun google-chrome http://webglsamples.googlecode.com/hg/aquarium/aquarium.html
# close window
google-chrome http://webglsamples.googlecode.com/hg/aquarium/aquarium.html
```

**Comment by MrMEEE** [comment]
Please add to ironhide:

Ubuntu Natty/Oneiric

sudo apt-get remove bumblebee
reboot
sudo apt-add-repository ppa:mj-casalogic/ironhide
sudo apt-get update && sudo apt-get install ironhide

Thanks

**Comment by Vanuan** [comment]
also add:

```
apt-get install dialog
```

or

```
apt-get install cdialog
```

**Comment by cement-head** [comment]
Where are / is the install & usage instructions?  Please help!

**Comment by MarceloRuiz** [comment]
I would also like to have a step by step instructions to install ironhide... Is that posted somewhere?
