### ISSUE TITLE
Asus N53S GT 550M

### ISSUE THREAD

**Issue by crappydrone** [MrMEEE/ironhide#90]
didn't quite manage to switch from noeuvau to nvidia-current

**Comment by MrMEEE** [comment]
???

**Comment by MrMEEE** [comment]
Please give more info??

**Comment by crappydrone** [comment]
Sorry for not posting, I found out that it worked shortly after I wrote this, and forgot about the post. The problem was that  the setup-GUI told me it had failed when it apparantly hadn't. 
I ran the testscript to find the correct commands for enabling/disabling the card, and when I went to /usr/local I found the correct scripts were there already, apparanlty having been put there by the automatic installation.
