### ISSUE TITLE
opengl demo lightspeed gives error at exit

### ISSUE THREAD

**Issue by linuxuser01** [MrMEEE/ironhide#92]
opengl demo lightspeed seems to run IK but does give an error at exit.  I have seen this type of error on exit with other programs when using optirun.

Light Speed! is an OpenGL-based program developed to illustrate the effects of special relativity on the appearance of moving objects. 

lightspeed is in standard Ubuntu repositories

When running program, in start dialog, be sure to select windowed mode instead of full screen.
- Full screen will change your monitor resolution settings

After install, in a cmd/term window run:
optirun lightspeed

program runs but at exit gives errors msgs in cmd/term window: 
optirun lightspeed
- Starting Ironhide X server ironhide  
  DON Enabling nVidia card succeeded.
             [ OK ](lightspeed:3392): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(lightspeed:3392): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(lightspeed:3392): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(lightspeed:3392): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

**--**  program runs but at exit gives the following messages in cmd/term window: 
terminate called after throwing an instance of 'rrerror'
/usr/bin/optirun: line 118:  3392 Aborted                 (core dumped) vglrun -c $VGL_COMPRESS -d $VGL_DISPLAY -ld "$VGL_DRIVER" "$@"
- Stopping Ironhide X server ironhide  
  _OFF Disabling nVidia card succeeded.

---

Hardware: ASUS N53sv-XV1 with nVidia Optimus (Intel/Nvida 540m)
OS: Ubuntu 11.10 (oneiric) beta2, updates as of Sept 25 2011, Unity desktop
Ironhide installed Sept 25 2011

**Comment by MrMEEE** [comment]
It works fine here...

there will be a new version of virtualgl available within the next hour... can you please confirm that this problem persists.??

**Comment by linuxuser01** [comment]
I updated to the new virtualgl.

optirun Lightspeed still runs but at exit the program still errors and dumps. I do not know how important this is or if it is a symptom of another issue.

The error and dump do not happen with lightspeed and no optirun

I am running Ubuntu 11.10 beta2 32 bit

**Comment by MrMEEE** [comment]
Should be fixed with virtualgl-2.2.99.. available now...

Please reopen, if problem persists...

**Comment by linuxuser01** [comment]
Yes, virtualgl-2.2.99 fixed the problem. The rrerror and dump errors are gone. The only messages now are not loacting theme engine

Thanks for the update
