### ISSUE TITLE
Chromium browser webgl does not work

### ISSUE THREAD

**Issue by linuxuser01** [MrMEEE/ironhide#93]
Using the open source Chromium browser instead of the Google branded Chrome browser.

Chromium is in standard Ubuntu repositories

This works
chromium-browser http://webglsamples.googlecode.com/hg/aquarium/aquarium.html

---

When using optirun, the browser starts but can not display the WebGL page. 
The browser gives an error page with message:
"It does not appear your computer supports WebGL."

--------   cmd/term window contents  ----------

optirun chromium-browser http://webglsamples.googlecode.com/hg/aquarium/aquarium.html
- Starting Ironhide X server ironhide  
  DON Enabling nVidia card succeeded.
      [ OK ]
  ERROR: ld.so: object 'libdlfaker.so' from LD_PRELOAD cannot be preloaded: ignored.
  ERROR: ld.so: object 'librrfaker.so' from LD_PRELOAD cannot be preloaded: ignored.

(chromium-browser:31327): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(chromium-browser:31327): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(chromium-browser:31327): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",

(chromium-browser:31327): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
[3:3:16072155933:ERROR:command_buffer_proxy.cc(106)] Could not send GpuCommandBufferMsg_Initialize.

---

Hardware: ASUS N53sv with Nvidia Optimus (Intel/Nvidia 540M
OS: Ubuntu 11.10 beta 2, updates Sept 25 2011, Unity Desktop

**Comment by MrMEEE** [comment]
Have you tried with optirun32??

might be connected to some of the multiarch problems..

**Comment by linuxuser01** [comment]
I am running Ubuntu 11.10 beta2 32bit.

When I try optirun32 I get "command not found"

**Comment by MrMEEE** [comment]
Seems to be a problem with some older versions...

I have the same problem with:

Chromium 13.0.782.215 Ubuntu 11.04
and
Google Chrome 13.0.782.112

But
Google Chrome 14.0.835.186 (http://www.google.com/chrome)
and
Chromium 14.0.835.126 Ubuntu 11.04 (https://launchpad.net/~chromium-daily/+archive/beta)

works just fine...

**Comment by linuxuser01** [comment]
Yes, Chromium 13.0.782.215 Ubuntu 11.10 32bit (13.0.782.215-r97094-0ubuntu2) from the standard Ubuntu repository worked when used directly but when this version was used with optirun, the WebGL stuff did not work.

I removed Chromium 13.0.782.215 and installed the version you suggested,
Chromium 14.0.835.126 Ubuntu 11.04 (https://launchpad.net/~chromium-daily/+archive/beta).

The WebGL in Chromium 14.0.835.126 beta does work with optirun and  http://webglsamples.googlecode.com/hg/aquarium/aquarium.html

Thanks
