### ISSUE TITLE
Gentoo support

### ISSUE THREAD

**Issue by ghost** [MrMEEE/ironhide#94]
Hi there,
bumblebee had support for different distributions, but it looks like ironhide is only supporting ubuntu..
Are you planning to support different distributions (in particular, I would be interested in gentoo support)..
Thanks!

davide

**Comment by MrMEEE** [comment]
Hi..

Ironhide will be limited to Ubuntu support.. As I feel this will make it easier to maintain..

You (or someone else) are welcome to fork the project and do Gentoo support...
