### ISSUE TITLE
Dell XPS 15z

### ISSUE THREAD

**Issue by cdebaes** [MrMEEE/ironhide#95]
Hello MrMEEE

First of all. Thanks for all the great work in ironhide so far. My set-up on Dell XPS 15z worked for only one time. Afterwards all attempts to load nvidia-current seem to be failing.  I've tried with all configurations of the database.

I'm willing to test things out from my side.

Yours,
cdebaes

**Comment by lunderlini** [comment]
In my case with gigabyte t1125,try

$sudo ironhide-settings

then change "Always enable the nVidia card before disabling" option to "No"
reboot and try again to work

**Comment by MrMEEE** [comment]
@cdebaes have you tried changing the option lunderlini suggests???

**Comment by MrMEEE** [comment]
Please reopen if the "Always enable the nVidia card before disabling" doesn't fix things for you...
