### ISSUE TITLE
Oil Rush don't start - again

### ISSUE THREAD

**Issue by BlueCase** [MrMEEE/ironhide#96]
https://github.com/MrMEEE/bumblebee/issues/314#issuecomment-2227397
One of the Oil Rush developer posted a feedback in the old bumblebee git to this topic...

regards,
Blue

**Comment by MrMEEE** [comment]
I have tried doing a virtualgl version 2.2.91 for natty 64-bit... I'm still having this problem:

Xlib:  extension "NV-GLX" missing on display ":0".
Xlib:  extension "NV-GLX" missing on display ":0".
X Error of failed request:  BadRequest (invalid request code or no such operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  34 ()
  Serial number of failed request:  81
  Current serial number in output stream:  82 
 AL lib: ALc.c:1879: exit(): closing 1 Device
 AL lib: ALc.c:1808: alcCloseDevice(): destroying 1 Context(s)

**Comment by jrudolph** [comment]
Martin,

in your ppa's package for some reason you have a huge diff which removes the important part for Oilrush (and probably others):

see your package's diff at

https://launchpadlibrarian.net/81547527/virtualgl_2.2.90-1~nattyubuntu2_2.2.91-1~nattyubuntu1.diff.gz

which is 80k big (!) and look at how you are removing `glXCreateContextAttribsARB` and more inside. Is that something you're doing on purpose? I could imagine you having a dirty workspace when creating the debs which somehow means that we end up with a virtualgl with much functionality removed.

BTW: I'm no developer of oilrush but I just tried it out some days ago and after I found it broken attached gdb and found out that `glXCreateContextAttribsARB` isn't handled by virtualgl for some reason...

**Comment by jrudolph** [comment]
Your new version `2.2.91-1~nattyubuntu2` works for me.

**Comment by MrMEEE** [comment]
@jrudolph: Great..

Also works here... I'll close this...

**Comment by BlueCase** [comment]
It works also for me now
But one question to you...
I use at the moment OilRush 0.80 and after a while i get a failure
NameSpace::check(): unused variable "Network::TEXT_MESSAGE_MARKER_ALL"
NameSpace::check(): unused variable "Network::SHUTDOWN_SERVER_LOCK"
NameSpace::check(): unused variable "Network::SERVER_REELECTION_LOCK"
NameSpace::check(): unused variable "Network::LOST_CONNECTION_LOCK"
NameSpace::check(): unused variable "Network::MAX_DROPPED_FLUSHES_RATE"
NameSpace::check(): unused variable "Network::MAX_DROPPED_FLUSHES_TIME"
NameSpace::check(): unused variable "Network::DECREASE_GAME_SPEED_STEP"
NameSpace::check(): unused variable "Network::MIN_GAME_SPEED"
Loading "waterwar/menu.cpp" 958ms
Received signal SIGSEGV, invalid memory reference
terminate called after throwing an instance of 'rrerror'
terminate called after throwing an instance of 'rrerror'
Aborted (core dumped)

One of you have the same failure or you tried it with a older version of OilRush=

**Comment by MrMEEE** [comment]
I'm not getting any errors??? using 0.80...

**Comment by MrMEEE** [comment]
Are you using Oneiric???

**Comment by BlueCase** [comment]
Yes and Yes

**Comment by MrMEEE** [comment]
There are some problems with Oneiric.. I haven't tested it at all...

I'll probably upgrade within a few weeks, and will look into Oneiric support then.....

**Comment by BlueCase** [comment]
Hi,
fyi
Oilrush 0,81 and the latest ironhide package work with Oneiric.

regards,
BlueCase
